### ISSUE TITLE
SRFI 252 rational-generator does not sample inexact-rational-generator.

### ISSUE THREAD

**Issue by a2379** [shirok/Gauche#1014]
On line 194 of 252.scm, rational-generator is an alias to exact-rational-generator, instead of sampling from both inexact-rational-generator and exact-rational-generator.

I can't tell if this is intentional or not, just wanted to make sure.

Thank you for implementing the SRFI!

**Comment by shirok** [comment]
Thanks, it is an oversight.  I wrote that line before I implement inexact-rational-generator, I guess.
