### ISSUE TITLE
cf-output needs better escaping

### ISSUE THREAD

**Issue by leahneukirchen** [shirok/Gauche#1028]
Two related issues related to `gauche.configure`:

If a configure definition is false (e.g. because the field in package.scm is missing, `cf-output` replaces `@DEFS@` with something like `-DPACKAGE_BUGREPORT=#f`.  When this variable is expanded, the shell treats `#` as a comment.

Likewise, if a configure definition contains a space, it is inserted as is: `DSTRING=\"foo bar\"`.
The shell performs word splitting and this breaks.

It is probably enough to prefix `#` and whitespace with `\`.

**Comment by shirok** [comment]
Cf. https://github.com/shirok/Gauche/issues/736

**Comment by shirok** [comment]
I think false value in substitution variable is natural to be replaced with an empty string.  The general escaping issue is a bit difficult, for it requires different handling depending on the context.

**Comment by shirok** [comment]
Regarding `cf-define` substitution - actually we can change escaping strategy for `@DEFS@` and `config.h`.
