### ISSUE TITLE
Printing content of hashtables/treemaps

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#1032]
Currently, print method of hashtables/treemaps only prints opaque object.  We avoid printing their contents initially, since we didn't have pprint and priting hash table contents by default could produce huge output that holds REPL long time.  But now that we have pprint by default, it's worth to allow printing their contents.

Another issue is that hashtables/treemaps can have arbitrary comparators, which may not have external representation.  We could check if it has "well-known" comparator or not, and prints unreadlabe object in place of the comparator if it's a custom one.

Related: https://github.com/shirok/Gauche/issues/892

Original suggestion: https://chaton.practical-scheme.net/gauche/a/2024/05/14#entry-66438f91-e6236

**Comment by shirok** [comment]
Handling pprint recursion into bultin print handler has several complications.  An alternative idea is to keep built-in print handler for hashtable and treemap intact, and handle them specially in the pprint routine.   Since the output of hashtables and treemaps are not readable, priting their contents is only worth with pprint anyway.

**Comment by shirok** [comment]
Letting `pprint` to handle dictionary display seems working well.  Let's close this one.

**Comment by leahneukirchen** [comment]
Very small nit:

```
gosh$ (hash-table-r7 'eq? 'a 'b 'c 'd)
#<hash-table eq[2]( (a . b) (c . d))>
```

The spacing of the first ( seems off?

**Comment by shirok** [comment]
That's because of the way the current pprint works.  The trick is that we don't just layout the content part by pprint, which _would_ produce:

```
#<hash-table eq[2] ((a . 1) (b . 2)
                    (c . 3) (d . 4)
                    (e . 5) (f . 6)
                    (g . 7))>
```
Instead, we treat the leading part as a part of layout, which produces:

```
#<hash-table eq[2]( (a . 1) (b . 2)
  (c . 3) (d . 4) (e . 5) (f . 6)  (g . 7))>
```
I see the latter is easier to see when the table has lots of items.   That extra whitespace is actually the 'breakable
whitespace' inserted by pprint.

If it is too bothering, I can add 'zero-width breakable whitespace' in pprint to eliminate that.  It would be a farily independent task from other parts, so I'm kind of "sit and see how it works" mode.

**Comment by leahneukirchen** [comment]
That's okay then! 😅
