### ISSUE TITLE
Hide sensitive info from `-V` output

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#1042]
The output of `gosh -V` contains Gauche's installation direcotries, which may include username or project name.  Since the output may be casually copied to bug reports etc., it may reveal those info unintentionally.

User-specific installation directory isn't really useful to reproduce troubleshooting (unless it's from a trouble with some weird pathnames), we may provide a way to exclude those from the output.  Some environment variables may do.

Relevant items: directory names of `--prefix` etc. of `build.configure`, paths in `scheme.path`.

**Comment by lassik** [comment]
One suggstion is for `-V` to show only basic info, and `-VV` to show more detail.

**Comment by lassik** [comment]
Unfortunately SRFI 176 does not have a standard solution to this problem, and there isn't a de facto standard among its implementors.

**Comment by shirok** [comment]
I think it's difficult to standardize what's sensitive, for it depend on too many factors.  Providing users to customize the default output (`-V`), while allowing full dump (e.g. `-VV`) in case to support a specific user case, would be enough.
