### ISSUE TITLE
ffitest error on Fedora 40

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#1044]
Reported from a user.

```
Testing ffitest ...                                              failed.
9 discrepancies found:
test load-foreign: expects (#t (f_i () i) (f_i_i (i) i)) => got #<<error> ": no matching clause for (.struct _IO_cookie_io_functions_t () ((read (.pointer () (.type cookie_read_function_t () (.function () (.type __ssize_t () (long ())) ((__cookie (.pointer () (void ()))) (__buf (.pointer () (char ()))) (__nbytes (.type size_t () (u-long ())))))))) (write (.pointer () (.type cookie_write_function_t () (.function () (.type __ssize_t () (long ())) ((__cookie (.pointer () (void ()))) (__buf (.pointer () (char (const)))) (__nbytes (.type size_t () (u-long ())))))))) (seek (.pointer () (.type cookie_seek_function_t () (.function () (int ()) ((__cookie (.pointer () (void ()))) (__pos (.pointer () (.type __off64_t () (long ())))) (__w (int ()))))))) (close (.pointer () (.type cookie_close_function_t () (.function () (int ()) ((__cookie (.pointer () (void ()))))))))))">
test call-foreign f_c: expects 9 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_i: expects 42 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_f: expects 1.25 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_d: expects 3.14 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_v: expects #<undef> => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_i_i: expects 99 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_f_f: expects 0.125 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
test call-foreign f_d_d: expects 1.0 => got #<<error> "flib is supposed to be of type #<class <foreign-library>>, but got #f">
```

My guess is that our C parser misses to recognize some patterns.

**Comment by SwitchAxe** [comment]
Hi, i get this error too on Opensuse Tumbleweed with the exact same output while trying to build Gauche. Is there any fix for this?

**Comment by shirok** [comment]
There seems a difference in a gcc header file and I couldn't reproduce it yet.  
Could you do me a favor?  Create a file `foo.c` with this single line:

```
#include <stdio.h>
```

And run this command:

```
cpp -E t.c > t.p
```

Then attach the output `t.p` here?

**Comment by shirok** [comment]
Oops, we stepped on to each other.
Could you try git HEAD? It worked with Fedora 40.

**Comment by SwitchAxe** [comment]
> Oops, we stepped on to each other. Could you try git HEAD? It worked with Fedora 40.

trying `sudo bash get_gauche_sh. --version snapshot` fails at the same spot as previously (i.e. the ffitest check) if that's what you're asking. What do you mean exactly by "trying git HEAD"? should i try to manually compile gauche from a fresh git clone?

**Comment by SwitchAxe** [comment]
> I think I fixed this. When you want to build git HEAD, install Gauche 0.9.15 without test (`get-gauche.sh --skip-tests`) first; the ffitest error doesn't affect normal operations.

Yes, Gauche builds successfully if I skip the tests, but it doesn't really sound like a proper solution to me... also considered that AFAIK there's no way to explicitly select which tests to skip, so if I want to skip ffitest, the build process skips all the tests, which is clearly undesirable under normal circumstances

**Comment by shirok** [comment]
To build from git HEAD you need the latest Gauche.  So, unless you already have 0.9.15 installed on your machine, you need:

- Install 0.9.15 by `get-gauche.sh --skip-tests`
- git clone the HEAD and build it (see `HACKING.adoc`).

The 'snapshot' build, that works with `get-gauche.sh --version snapshot`, needs to be explicitly created.  This may be entitled for `0.9.15-p2`, actually.  The above two-step installation is a nusance.
There's a plan to make nightly build available but not implemented yet.  https://github.com/shirok/Gauche/issues/1008

**Comment by SwitchAxe** [comment]
> To build from git HEAD you need the latest Gauche. So, unless you already have 0.9.15 installed on your machine, you need:
> 
>     * Install 0.9.15 by `get-gauche.sh --skip-tests`
> 
>     * git clone the HEAD and build it (see `HACKING.adoc`).
> 
> 
> The 'snapshot' build, that works with `get-gauche.sh --version snapshot`, needs to be explicitly created. This may be entitled for `0.9.15-p2`, actually. The above two-step installation is a nusance. There's a plan to make nightly build available but not implemented yet. #1008

ok, i installed the latest Gauche release and then built git HEAD and it builds with no errors

**Comment by shirok** [comment]
Thanks.  I'm also working on providing "bleeding edge" snapshot tarball, so that users won't need those two-step process.

Closing.
