### ISSUE TITLE
MbedTLS 3.6.0 doesn't work with Gauche

### ISSUE THREAD

**Issue by Junker** [shirok/Gauche#1047]
```
*** ERROR: mbedtls_ssl_read() failed: SSL - No data of requested type currently available on underlying transport (-26880)
Stack Trace:
_______________________________________
  0  (report-error e)
  1  (tls-read tls)
  2  (read-line remote)
        at "/usr/share/gauche-0.98/0.9.15/lib/rfc/http.scm":820
  3  (parse-status-line (read-line remote))
        at "/usr/share/gauche-0.98/0.9.15/lib/rfc/http.scm":820
  4  (receive-header in)
        at "/usr/share/gauche-0.98/0.9.15/lib/rfc/http.scm":276
  5  thunk
  6  (with-connection conn (^ (i o) (request-response i o method u ...
        at "/usr/share/gauche-0.98/0.9.15/lib/rfc/http.scm":303
  ...
```

With MbedTLS 3.5.2 have no problem.

**Additional info:**
OS: Arch Linux
Gauche: 0.9.15

**Comment by shirok** [comment]
Confirmed.

**Comment by shirok** [comment]
The difference I see so far is taht mbedtls 3.5.2 connects using TLS1.2, while 3.6.0 using TLS1.3.  A connectinon is esablished and HTTP request is sent successfully in both cases.  With 3.5.2, the server returns HTTP response.  With 3.6.0, the server returns post-handshale message (NewSessionTicket), and mbed sends an alert message, then the communication dies.

**Comment by shirok** [comment]
This may be relevant: https://github.com/Mbed-TLS/mbedtls/issues/9223

**Comment by shirok** [comment]
Fixed.  Feel free to reopen if you still see the symptom.
