### ISSUE TITLE
Allow passing environment to `run-process`

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#1071]
Need to have a variation of `Scm_SysExec` to take enviornment list (probably symmetric to what `(sys-environ)` returns).  We need to use `execve` instead of `execvp` (`execvpe` is not in POSIX).  That means we need to do our own `PATH` searching.  We can graft `find-file-in-paths` in `file.util` into core.

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer
