### ISSUE TITLE
Why "gosh" installs to ARCH directory?

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#108]
Why `gosh` and `libgauche-0.9.so` are installs `ARCH_INSTALL_DIR` ?
Is there are any reasons to install both of standard directory and ARCH directory?

**Comment by qykth-git** [comment]
It's interesting idea.
I think those multiple-version Gauche has similar structure to "portable application".

**Comment by shirok** [comment]
Since 0.9.6, gosh binary links to libgauche under ARCH_INSTALL_DIR.  This allows users to install multiple versions of Gauche.  ${bindir}/gosh is overwritten by the last installed Gauche, but using -v VERSION the user starts different version of Gauche.

Closing.
