### ISSUE TITLE
MinGW build failure

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#109]
This is FYI issue. Just close this issue if satisfied.

Current `master` branch will breaks MinGW build because of too old `autoconf`.

I think current MinGW is outdated. But I found there are MinGW-W64 ( http://mingw-w64.org/ )
and MSYS2 ( http://msys2.github.io/ ).

I think MinGW-W64 and MSYS2 will works well for current `master` branch.

**Comment by shirok** [comment]
At this moment, the source tree can be built with mingw-w64 and msys2.  Closing.
