### ISSUE TITLE
Circular dependency breaks compilation

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#111]
321a91131fb7b19785ad7b68b5301ec6f450fcff introduces circular dependency around `gauche.uvector` module.

It breaks compilation when builds from fully cleaned up source tree.

**Comment by shirok** [comment]
Oops, ok

**Comment by shirok** [comment]
How about 897e968?

**Comment by qykth-git** [comment]
It seems OK on my machine.

**Comment by shirok** [comment]
Thanks
