### ISSUE TITLE
Can't rebuild gauche from source

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#155]
Current (2085186000f6da54bd9e655bd4f9c88258b764ee) Unicode table generator `src/gen-unicode.scm` will not works with previous released version Gauche 0.9.4.
Because `gflatten` is not available in version 0.9.4 of `gauche.generator` module.

This error will breaks re-building Gauche from source code.

```scheme
*** ERROR: unbound variable: gflatten
Stack Trace:
_______________________________________
  0  (gflatten (gmap (^_ items) (giota c)))
        At line 720 of "../lib/text/unicode/ucd.scm"
```

**Comment by shirok** [comment]
Oops, my bad.

**Comment by shirok** [comment]
Fix pushed. https://github.com/shirok/Gauche/commit/8e441430cc67395ae78987af1d38f2700ed22e23
