### ISSUE TITLE
support more $TERM in text.line-edit

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#179]
I'm very happy to see Gauche starts to have some line editing capability. But it does not work out of the box for me because tmux set $TERM to screen. I suppose we can just add that to the recognized $TERM for now (it worked ok for me when I forced TERM to xterm, for example). I don't know if you can talk to screen/tmux to find out the actual term type, but I guess it's not that important.

Please also "support" rxvt-256color, by maybe relaxing the /^rxvt$/ pattern a a little bit.

Hope to see line editing in gosh soon!

**Comment by shirok** [comment]
I pushed https://github.com/shirok/Gauche/commit/33b06e4c04aa4b13fa051d39fa9a4937e64ad088

Let me know if you find more terminals that's work with <vt100>.  I'll add them as we go.
