### ISSUE TITLE
Hash function test fail

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#214]
Test failed on my 32-bit Linux machine.

I think it comes from a difference of internal floating point number format between 64bit and 32 bit architecture.
Please check `src/number.c:Scm_DecodeFlonum()` or some other point.

```scheme
Testing hash tables ===========================================================
<hash function>----------------------------------------------------------------
test portable hash, expects ((#f . 3428989595) (#t . 64744347) (#\a . 3754065427) (#\null . 3668339987) (0 . 2654435761) (1 . 387276917) (-1 . 626627309) (45174651375937459317569347657 . 3238994630) (1.1 . 2919879337) (-1.1 . 1375087959) (+inf.0 . 0) (+nan.0 . 0) (1/2 . 1401181143) (-5/4 . 91423867) (3.0+1.0i . 2027808452) (() . 995466395) ((#f a 0) . 509715512) (#(#t :b 3.2) . 1522869008) ("" . 0) ("zye" . 121094) (abc . 96354) (:foo . 101574)) ==> ERROR: GOT ((#f . 3428989595) (#t . 64744347) (#\a . 3754065427) (#\null . 3668339987) (0 . 2654435761) (1 . 387276917) (-1 . 626627309) (45174651375937459317569347657 . 3238994630) (1.1 . 2919879337) (-1.1 . 2147483648) (+inf.0 . 0) (+nan.0 . 2147483648) (1/2 . 1401181143) (-5/4 . 91423867) (3.0+1.0i . 0) (() . 995466395) ((#f a 0) . 509715512) (#(#t :b 3.2) . 1618609165) ("" . 0) ("zye" . 121094) (abc . 96354) (:foo . 101574))
```

**Comment by shirok** [comment]
The portable hash doesn't use DecodeFlonum().  My hunch is it's in somewhere around promoting ulong greater than INT_MAX to double; I'll check it on a 32bit machine.

Actually, I've found the old 'hash' produced different values in 64/32bits for bignums, and now flonums, too.  At this point I may well consider breaking backward compatibility and fix the legacy_number_hash once and for all.

**Comment by shirok** [comment]
Could you give me the spec of your machine?  I can't reproduce the discrepancy.

My machine: Core Duo with Ubuntu 16.04
gcc (Ubuntu 5.3.1-14ubuntu2.1) 5.3.1 20160413
./config-guess output : i686-pc-linux-gnu

gosh> (hash -1.1)
1375087959

Your result, (hash -1.1) => 2147483648, is (ulong)(INT_MIN) on 32bit machine, so it may be possible that my code is triggering undefined behavior and the different version of gcc takes different way to take advantage of the UB.

**Comment by qykth-git** [comment]
I use Core2 with GCC 5.4.0.

I re-check my compilation environment, and I found why this test failure happens.
It comes from SSE enhancement option.

When I compile with those options, It works well.
```sh
./configure CFLAGS="-g -O2 -march=core2" --disable-heuristic-optimization
```

But those are produces test failure.
```sh
./configure CFLAGS="-g -O2 -march=core2 -mfpmath=sse" --disable-heuristic-optimization
```

This test failure also happens on GCC 6.
I think this test failure comes from the difference between standard 387 FPU and SSE.

**Comment by shirok** [comment]
Oh I didn't know I could use -march=core2 with 32bit processors.  Yeah, I confirmed the result.
The culprit is CVTTSD2SI insrutction, which converts double flonum in SSE register
to integer and stores a general register.  On 32bit processors, when the flonum is out of range
and FPU trap is masked, 0x80000000 is stored to the general register, which is what's happening.

It seems casting double to ulong is UB if the source is out-of-range, so I need to change that part
anyway.

**Comment by shirok** [comment]
Fix pushed.
