### ISSUE TITLE
Where can i find documentation for old version

### ISSUE THREAD

**Issue by yang-wei** [shirok/Gauche#272]
I am currently looking for 0.9.3.3 documentation but couldn't find anything on the web.
Please let me know if you do have =)

**Comment by shirok** [comment]
We don't keep online doc of older releases, but you can download 0.9.3.3 tarball and build the doc by yourself.
https://sourceforge.net/projects/gauche/files/Gauche/Gauche-0.9.3.3.tgz/download

**Comment by yang-wei** [comment]
arigatou !
