### ISSUE TITLE
string-prefix? does not work as documented

### ISSUE THREAD

**Issue by kannokanno** [shirok/Gauche#284]
Hi.

I use `string-prefix?`.
The document says that.

> Function: string-prefix? s1 s2 :optional start1 end1 start2 end2
> Function: string-suffix? s1 s2 :optional start1 end1 start2 end2
> Function: string-prefix-ci? s1 s2 :optional start1 end1 start2 end2
> Function: string-suffix-ci? s1 s2 :optional start1 end1 start2 end2
>
> [SRFI-13] Returns true iff s2 is a prefix or suffix of s1, respectively. The optional arguments limit the range of s1 and s2 to look at. The *-ci variations use case foling character comparison.
>
> (string-prefix? "scheme" "sch")   ⇒ #t

http://practical-scheme.net/gauche/man/gauche-refe/String-library.html#String-library

But actually trying it looks like s1 and s2 are opposite.

```scheme
gosh> (use srfi-13)
; expected #t but #f
gosh> (string-prefix? "scheme" "sch")
#f

gosh> (string-prefix? "sch" "scheme")
#t
```

Whether the document is incorrect or the implementation is incorrect.

Thanks.

## version

```
$ gosh -V
Gauche scheme shell, version 0.9.5 [utf-8,pthreads], x86_64-apple-darwin15.6.0
```

**Comment by shirok** [comment]
It has been fixed in HEAD.  Thanks anyway.

**Comment by kannokanno** [comment]
I understand. Thanks.

**Comment by shirok** [comment]
I know it is confusing, isn't it?  0.9.6 release is pretty close.
