### ISSUE TITLE
Build failure with uClibc

### ISSUE THREAD

**Issue by baruchsiach** [shirok/Gauche#287]
uClibc does not provide the `gnu/libc-version.h` header. Yet, uClibc does define `__GLIBC__`. This leads to the following build failure:

```
In file included from ./include/private/gc_priv.h:94:0,
                 from checksums.c:14:
./include/private/gcconfig.h:1426:72: fatal error: gnu/libc-version.h: No such file or directory
```

Upstream bdwgc fixed this issue in ivmai/bdwgc@047230b71d42140.

**Comment by shirok** [comment]
Applied upstream fix.  Thanks.
