### ISSUE TITLE
Cannot compile documentation into a PDF

### ISSUE THREAD

**Issue by kozross** [shirok/Gauche#295]
After running ``./configure`` followed by ``make`` and ``cd``ing into ``doc``, I tried ``texi2pdf *.texi``, but got this error:

```
[koz@Sebastian doc]$ texi2pdf *.texi
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdfetex)
 restricted \write18 enabled.
entering extended mode
(./concepts.texi
./concepts.texi:28: Missing $ inserted.
<inserted text> 
                $
<to be read again> 
                   ^
l.28 Gauche conforms "Revised^
                              7 Report of Algorithmic Language Scheme,"
? X
No pages of output.
Transcript written on concepts.log.
/usr/bin/texi2dvi: pdfetex exited with bad status, quitting.
```
Am I doing something wrong? I have TeXLive version 2017.44590-1 installed on Arch Linux.

**Comment by shirok** [comment]
Under doc, try "make pdf".

**Comment by kozross** [comment]
```
[koz@Sebastian doc]$ make pdf
../src/gosh -q -ftest ./extract.scm -en -o gauche-refe.texi ./gauche-ref.texi
make: *** [Makefile:119: gauche-refe.texi] Segmentation fault (core dumped)
```

**Comment by shirok** [comment]
Hmm, weird.  Are you building 0.9.5, or HEAD? (Both works on Ubuntu).
Also, after "make", could you run "make -s check" to make sure it is built properly?

**Comment by kozross** [comment]
I'm building HEAD (what I got after running ``git clone``). When I tried to run ``make -s check``, I got this:

```
[koz@Muni Gauche]$ make -s check
make[2]: *** [Makefile:25: util--match.c] Segmentation fault (core dumped)
make[1]: *** [Makefile:37: util] Error 2
make: *** [Makefile:40: all] Error 1
```

To get to this point after cloning and ``cd``, I did ``autoreconf -fi``, then ``./configure``, then ``make`` followed by ``make -s check``.

**Comment by qykth-git** [comment]
Don't use `autoreconf`. Because Gauche requires some special tweaks for GC library.
Use `./DIST gen` to build `configure` script.
Read document [HACKING](../blob/master/HACKING) for more details.

**Comment by kozross** [comment]
@qykth-git Thanks - after doing that from a clean clone (and a few Makefile changes in ``doc``), the documentation built successfully.
