### ISSUE TITLE
Gauche's website should offer a PDF download of the manual

### ISSUE THREAD

**Issue by kozross** [shirok/Gauche#296]
I like having offline documentation, and PDF is a pretty good format for that. Given that Gauche's documentation is written in Texinfo, it can easily be built into a PDF. This currently requires me to clone the source and build it myself. Would it be possible to have PDF documentation downloadable from the Gauche site?

**Comment by shirok** [comment]
Sure if users want it.  Just to clarify---if you install Gauche, you do have offline documentation in the form of info, which you can browse from terminal, emacs (with some macro you can directly lookup items from you r Gauche source), or from gosh REPL (",info" or ",doc" toplevel commands).  You'd still prefer having separate pdf document?  (I'm not saying that's a problem. Just to get the sense of demand.)

**Comment by kozross** [comment]
I like having a PDF for my Android tablet. I have long commutes, and obviously public transport means no wifi. I also can't (easily) install Gauche on my tablet, because Android is silly. Thus, a PDF is great. I admit my needs seem a tad niche, but given that your build can already make PDFs, why not?

**Comment by shirok** [comment]
Aha, that use case I haven't thought of.  Thanks for letting me know.  Yes, I can build pdf along the release procedure and put up on the server.
