### ISSUE TITLE
About #308 (Windows console code page support)

### ISSUE THREAD

**Issue by Hamayama** [shirok/Gauche#309]
日本語ですいません。

#308 の Windows console code page support の件ですが、
Revert した方がよいかなという気がしています。
最初はよいアイデアだと思ったのですが。。。

REPL上では日本語が使えてよいのですが、同じ入力をスクリプトファイルにすると、
化けてしまいます。

それで 例えば、スクリプトファイルを、
```
;; -*- coding: utf-8 -*-
(cond-expand
 [gauche.os.windows
  (display #\cr)(flush) ; allocate console for windows
  (use gauche.interactive.windows)
  (wrap-windows-console-standard-ports)]
 [else])

(print "日本語を入力してみてください。")
(flush)
(print "「" (read-line) "」が入力されました。")
(print "[Enter]キーで終了します。")
(flush)
(read-line)
```
のように書けばいけると思うのですが、多分ユーザーはこのように書くことを
気が付かないし、REPLではいけているので、かえって混乱するような気がします。

上記の (cond-expand ...) の部分をスクリプトの起動時に自動で走らせることも
検討してみたのですが、.scm ファイルをダブルクリックすると、gosh-noconsole
が起動するため、実行するタイミングがありませんでした。
(trapper_flusher のところで実行してみたりしたのですが、この時点ではもう
 表示直前なので、ここでポートをラップしても間に合わない。。。)
(ただ、自分は gosh-noconsole 自体は、とても気に入っています)

ユーザーがコードを書いて対応するということであれば、もともと msjis 
モジュールで対応が可能でした。
これを取り込むと考えたとしても、
gauche.interactive.windows
という場所はどうなのかと。。。

一回元に戻して、仕切りなおそうと思うのですが、どうでしょうか。
(元に戻す場合は、プルリクエストはこちらで作成します)

**Comment by shirok** [comment]
なるほど。まだ検証環境を作っていないので、この件についてはHamayamaさんの分析を信頼します。
一度revertして仕切り直しということであればそれでokです (コミットログを綺麗に…とかあんまり考えてないので気にしないでください)。revertのPRを下さい。
このissueのurlもログに含めておいて頂ければ。

**Comment by Hamayama** [comment]
merge ありがとうございます。
また、何かよい方法が思いついたら、やってみようと思います。
