### ISSUE TITLE
f64vector size limit by 8 GB?

### ISSUE THREAD

**Issue by crocusino** [shirok/Gauche#352]
`(use srfi-4)`
`(define v1 (make-f64vector (* 1024 1024 1023)))`
`(f64vector-length v1)` gives `1072693248` i.e. `(* 1024 1024 1023)` and correctly corresponds to 8*1023 MB

while

`(define v1 (make-f64vector (* 1024 1024 1024)))`
`(f64vector-length v1)` gives `-1073741824` WRONG

As if length variable is internally `signed int`. It should rather be `size_t`, not?

**Comment by shirok** [comment]
You're right.  Thanks.  Fixed.
