### ISSUE TITLE
sxml document mentions non-existent sxpath1 and sxpathr

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#356]
sxpath document lists examples including sxpath1 and sxpathr which can't be found in the source code. I guess it's some old form that has been long replaced. I'm not sure if I will have to use sxpath in my project. If so I'll try to find out how to update these examples.

**Comment by shirok** [comment]
That part of the document is lifed from sxpath source, and it isn't an example but is specifying the behavior in terms of rewriting rules.  sxpath1 and sxpathr is not API but nonterminals.  It is certainly confusing, so I'll add description.

sxpath is handy but I myself often get lost when I try to write a complex query.  But there's an escape hatch---you can just pass XPath query string to sxpath.

**Comment by pclouds** [comment]
Ah.. I searched for it in the document, didn't see it mentioned anywhere and assumed. Thanks for the clarification.
