### ISSUE TITLE
`,info` fails if $PAGER has flags

### ISSUE THREAD

**Issue by mnacamura** [shirok/Gauche#357]
Hi,
```
% echo $PAGER
less -R -ig -j.5
% gosh
gosh> ,info let1
exec failed: less -R -ig -j.5: No such file or directory
```
In `lib/gauche/interactive/info.scm `, `*pager*` should be passed to `string-split`?

**Comment by shirok** [comment]
Good catch.  Didn't think about the case.
There can be a case that you want to use a command that includes whitespaces in its path, so I'd probably go with `shell-tokenize-string`.
