### ISSUE TITLE
Default server certificates

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#365]
We want to make it easy to use client TLS.  Can we do better than asking each user to download a cert bundle and tell its path to Gauche intidividually?

- Bundle our own certs in Gauche distro --- easy to the users, but not desirable as it's difficult to let it updated timely.
    - It might be an option to provide a simple script to download a bundle (e.g. curl's) and put up in our location.  We can delegate secure downloading to other tools as curl.  Users can kick the script to update the bundle.
- Piggyback to the certs of existing tools.
    - On Ubuntu, /etc/ssl/certs/ca-certificates.crt looks suffice.  How universal is it?
    - OSX seems to have its own framework.
    - Windows?

We could also honor SSL_CERT_FILE env var to share certs with openssl.

**Comment by qykth-git** [comment]
Here is Windows PowerShell script to piggyback CA certificate from local machine.
Output file is named `gauche-ca-cert.crt`.

```powershell
Get-ChildItem cert:\LocalMachine\AuthRoot | ForEach-Object {
    Write-Output '-----BEGIN CERTIFICATE-----'
    [System.Convert]::ToBase64String($_.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
    Write-Output '-----END CERTIFICATE-----'
} | Set-Content gauche-ca-cert.crt
```

**Comment by shirok** [comment]
I think the best way to go is to piggyback on system's or popular browser's; here I mean we directly use them (not creating our own file from it).  Then updating root certificates is done by the platform's normal updating process.

If we do need to create intermediate file, there should be a mechanism to check whether it's up to date or not, and possibly regenerate it if the source is updated.

**Comment by pclouds** [comment]
I came across this and got curious. With qykth-git PR, is this problem solved and this issue should be closed?

**Comment by shirok** [comment]
I think I left this open until I can think of a nice default behavior that "just works" for typical cases on all systems, without special configuration.

**Comment by shirok** [comment]
I think I can close this.

- Now we search several well-known ca-bundle files on the system by default.
- A script `rfc/tls/get-cacert.scm` is provided for users who wish to get ca-bundle file in Gauche installation tree.

We can add heuristics as we find the cases when the current default fails to work out of the box.
