### ISSUE TITLE
Wrongly expand feature identifier when cross-compiling

### ISSUE THREAD

**Issue by qykth-git** [shirok/Gauche#407]
For example, Linux have `lchown(2)`, and Windows dosen't have this function.
When I cross-compile to build Windows executable and type `(use file.util)`, the executable uses `sys-lchown` and produces error.
```
gosh> (use file.util)
*** ERROR: unbound variable: sys-lchown
    While loading "...\\share\\gauche-0.97\\0.9.7_rc1\\lib/file/util.scm" at line 5
    While compiling: (use file.util)
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "...\\share\\gauche-0.97\\0.9.7_rc1\\lib/gauche/interactive.scm":269
```

I think something wrong in feature-expansion when cross-compiling.

**Comment by qykth-git** [comment]
I think those tailored feature list might be generate from `src/gauche/config.h`.
Because `configure` script checks features and write this file.

**Comment by shirok** [comment]
Yeah, either post-process gauche/config.h or generate one during configure run.  I want to push out 0.9.7 now, though, so I'd carry it over after the release.

**Comment by shirok** [comment]
I implemented the idea of taking feature flag values from config.h in the commit https://github.com/shirok/Gauche/commit/b040649433e2974348e19bab8fb1775cbcd8af98

Cross-compiling `./configure --build=x86_64-pc-linux-gnu --host=i686-w64-mingw32` seems to work, but not extensively tested.  Could you play with it when you have time?

**Comment by qykth-git** [comment]
Thanks.
It works well on MS-Windows and Wine.

build: x86_64-pc-linux-gnu
host: x86_64-w64-mingw32

**Comment by shirok** [comment]
I close this.  If you stumble on similar issues, create a new one and refer to this.
