### ISSUE TITLE
new option in gauche-package compile to stop after generating C stub

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#427]
Stub/CiSE API is unfortunately far from perfect, to the point that I would not need to look at generated code at all when something goes wrong. On old extensions I use "genstub" then compile separately and I can examine generated code to find the problem. But with the new "gauche-package compile", the C files generated by *.stub are always removed even when compile fails, it's just impossible to know what's wrong some times (unless I fall back to "gosh genstub" again, which is not ideal).

Since we already have an option to stop after compile (i.e. no linking) we could go one step further and add an option to stop after stub generation and not compile. This is I think quite similar to -E vs -c in gcc.

While at there, I would appreciate a command line option to stop generating `#line` in generated code. It helps C compiler point to the exact problematic code (sometimes the associated Scheme line does not make much sense). I know there's `cise-emit-source-line` so I guess this is quite trivial, once we figure out the right option name.

**Comment by shirok** [comment]
Indeed.  Thanks for bringing it up.  I occasionally find myself running 'gosh genstub' separately just to look at the generated C code.  It's about time to implement it.

**Comment by shirok** [comment]
Added a new option -k | --keep-c-files to leave the intermediate C files, and --no-line to suppress #line directives.
Do we need an option to just generate C files and stop?

**Comment by pclouds** [comment]
> Do we need an option to just generate C files and stop?

Probably not. It sounds neat since gcc also has `-E` but I would be just as happy with `-k`.

**Comment by pclouds** [comment]
Typo somwhere

```
$ gauche-package compile -c foobarlib.stub
*** ERROR: unbound variable: no-lien
Stack Trace:
_______________________________________
  0  no-lien
        [unknown location]
  1  (x (cddr args))
        [unknown location]
```

**Comment by pclouds** [comment]
I'm closing this since it's working for me and you're probably just too nice, thinking  closing it would upset me ;) If you want to leave it open because you plan to generate C files and stop, of course you can reopen.

PS. the precomp feature should be coming soon to `gauche-package` (or to extension development anyway, if it's not accessible via gauche-package command), right? right? ;-)
