### ISSUE TITLE
Possible bug in file src/libsys.c line 2850

### ISSUE THREAD

**Issue by petrufm** [shirok/Gauche#446]
While experimenting with a novel static analysis technique in CodeSonar, we noticed the following potential problem at the next location:

FilePath: src/libsys.c (probably generated from src/libsys.scm)
Function: libsyssys_getloadavg (probably generated from sys-getloadavg)
Line number:2850 (probably generated from line 507)

Shouldn't you print using the Scm_Error function the value of *n*samples instead of samples?

Thanks,
Petru-Florin Mihancea

**Comment by shirok** [comment]
Indeed it was a bug.  Thanks for letting us know.  Praise the static analyzer!

**Comment by petrufm** [comment]
:). Thanks!
