### ISSUE TITLE
Partial continuation and dynamic-wind

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#477]
When the control goes out of dynamic scope with `shift`, should the dynamic-wind after thunk be called?  (probably yes)

https://twitter.com/ayatoy/status/1131585474814812161

**Comment by Hamayama** [comment]
部分継続と動的環境の件について、少し調べてみました。

- **case1:**  
  dynamic-wind の after が呼ばれない。
  ```
  (use gauche.partcont)
  (define k1 #f)
  (reset (dynamic-wind
          (lambda () (display "[d01]"))
          (lambda () (display "[d02]")
                     (shift k (set! k1 k) #f)
                     (display "[d03]"))
          (lambda () (display "[d04]"))))
  ;; ==> [d01][d02]#f
  ;;     ([d04]が呼ばれない)
  (k1)
  ;; ==> [d01][d03][d04]#<undef>
  ;;     (OK)
  ```


- **case2:**  
  明示的に部分継続を起動した場合には、after が呼ばれるようです。
  ```
  (use gauche.partcont)
  (define k1 #f)
  (reset (dynamic-wind
          (lambda () (display "[d01]"))
          (lambda () (display "[d02]")
                     (shift k (set! k1 k) (k #f))
                     (display "[d03]"))
          (lambda () (display "[d04]"))))
  ;; ==> [d01][d02][d03][d04]#<undef>
  ;;     ([d03]が呼ばれてしまう)
  (k1)
  ;; ==> [d01][d03][d04]#<undef>
  ;;     (OK)
  ```
  ただ、これだと部分継続の内容([d03])を、実行してしまいます。。。


- **case3:**  
  reset の直後に脱出用の (shift k0 ... を追加して、
  k0を明示的に起動するようにすれば、
  今回のケースについては、望んだ動作になるようです。
  ```
  (use gauche.partcont)
  (define k1 #f)
  (reset (shift
          k0
          (dynamic-wind
           (lambda () (display "[d01]"))
           (lambda () (display "[d02]")
                      (shift k (set! k1 k) (k0 #f))
                      (display "[d03]"))
           (lambda () (display "[d04]")))))
  ;; ==> [d01][d02][d04]#f
  ;;     (OK)
  (k1)
  ;; ==> [d01][d03][d04]#<undef>
  ;;     (OK)
  ```


すなわち、現状の Gauche では、  
「部分継続を起動することなく shift の expr ... をするっと抜けた場合に、  
動的環境の脱出/再入処理が行われない」
ということになるかと。

ちょっと、どうするべきかまでは、考えられていませんが、
まずは、情報としてあげておきます。

**Comment by Hamayama** [comment]
別パターン。
以下では、部分継続から戻るときに before が呼ばれない。

- **case 2-A:**  
  before が1回、after が 2回呼ばれる。
  (例えば、parameterize で parameter がうまく復帰しない (2回復帰するので元に戻ってしまう) 等の症状が出る)
  ```
  (use gauche.partcont)
  (reset (shift
          k0
          (dynamic-wind
           (lambda () (display "[d01]"))
           (lambda () (display "[d02]")
                      (k0 #f)
                      (display "[d03]"))
           (lambda () (display "[d04]")))))
  ;; ==> [d01][d02][d04][d03][d04]#<undef>
  ;;     ([d01]が1回、[d04]が2回呼ばれる)
  ```

ただ、これを Racket ((require racket/control) が必要) で実行すると
[d01][d02][d03][d04] になる。

つまり、(k0 #f) で after が呼ばれることの方が、問題なのかもしれない。

ちょっとまだ、仕様が把握できない感じ。
以下が、関連しそうですが。。。
https://twitter.com/dico_leque/status/1132089714767384576

**Comment by shirok** [comment]
部分継続とdynamic-windの関係を明確に論じたものは無かったように思います。少なくとも初期の部分継続論文ではdynamic-windは考慮されていません。もしかするとRacket勢が何か新しい論文出しているかもしれませんが…
なので手探りでやるしかないんですが、一応Gaucheでは部分継続で切り取る時に動的環境のチェインも切り取っておいて、出入りする際に辻妻を合わせようとはしています。ただ仕様自体をちゃんと考えてないんで抜けがある感じですね。
まずは論文のサーベイからかな…
