### ISSUE TITLE
Too generic error message from record accessor

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#488]
Consider this short program

```scheme
(use srfi-99)
(define-record-type foo (make-foo) #t (abc) (def))
(define-method write-object ((obj foo) port)
  (display (foo-abc obj) port)
  (display (foo-def obj) port))
(define rec (make-foo))
(foo-def-set! rec 2)
(print rec)
```

which shows

```
*** ERROR: Error occurred in error handler
    While loading "./test.scm" at line 8
Stack Trace:
_______________________________________
  0  (foo-abc obj)
        at "./test.scm":4
```

This generic error message does not really help fix the problen ('abc' field not defined). If `(ref obj 'abc)` is used instead of `(foo-abc`, then I got

```
*** ERROR: slot abc of object of class #<class foo> is unbound
    While loading "./test.scm" at line 8
```

which is much better.

Side problem, if I do `(foo-abc #?=obj)` instead, it looks like it enters an infinite loop, which ends with segfault.

**Comment by shirok** [comment]
That's actually not a generic error message; it is catching a double fault, .e.g the last resort.
The error handler tries to print the offending object, which triggers write-object method that caused another error.  Guess I should be more careful about printing the offending object.

**Comment by pclouds** [comment]
Ah! I forgot that this write-object could in turn be used by the error handler. Makes sense. Feel free to close it if you think nothing needs to be done (probably so).

**Comment by shirok** [comment]
I feel I can improve something---the current situation gives little clue of what's happening.

**Comment by pclouds** [comment]
PS. Java I think has something like that. When an exception is thrown sometimes I think I see

 exception blah blah blah
 long stack trace
 thrown from here
 more stack trace

**Comment by shirok** [comment]
The reason of double fault is that the error message of unbound slot tried to print the object, which calls write-object method of the object recursively.   I pushed a couple of patches to alleviate the problem.

The infinite recursion of using #?=obj in write-object is a supposed behavior---you literally invoke write-object inside write-object. 

The Java's exception is a different story.  Java tends to catch an exception and wraps it with another exception and throw it, so the catch clause gets nested exceptions.  The checked exception feature may encourage such style (but it's sometimes awful).  The double fault in our case is detected when error procedure is called during error handling, so we don't have the nested exception object at the time we see the double fault.
