### ISSUE TITLE
char-set:digit does not follow srfi-14 and only covers ascii

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#496]
From SRFI-14

> In Unicode, a character is a digit if it has the category Nd in the character attribute database. In Latin-1 and ASCII, the only such characters are 0123456789. In Unicode, there are other digit characters in other code blocks, such as Gujarati digits and Tibetan digits.

But Gauche's `char-set:digit` currently returns only [0-9].

Chibi Scheme as an SRE test about this digit charset where it tries to match non-ascii digits. For full complicance we may need to fix this. Bottom low priority of course, I don't think many people really use non-ascii digits.

**Comment by shirok** [comment]
Right.  Contrary to the comment in char.c that states we only define the ascii range for the predefined character sets, I've already changed most char sets to cover full Unicode.

I don't quire remember why I didn't change digit, but my guess is that char-set:digit also affects the interpretation of \d and \D in the regexp, and changing it can have unexpected consequences.  Notably, \d is used for validations of input assuming only ascii digits, and allowing extended unicode digits will potentially create a new attack vector.

My current idea is to create ascii-digits and digits, and use ascii-digits for \d.
