### ISSUE TITLE
char-set-intersection (or -union) does not work reliably

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#497]
Consider the two examples, they should have identical results in my opinion, but they return different results now

```scheme
(print (char-set-intersection
        (char-set-union (string->char-set "_")
                        char-set:letter+digit)
        char-set:full))
(print (char-set-intersection
        (char-set-union char-set:letter+digit
                        (string->char-set "_"))
        char-set:full))
```

The first one returns correctly. The second one seems to return just the ascii part, `#[0-9A-Z_a-z]`

**Comment by shirok** [comment]
#500 did fixed it.    Test added.  Closing.
