### ISSUE TITLE
Use `let-values` instead of `receive` in documentation?

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#520]
Gauche documentation uses `(receive ...)` in a few places to bind multiple return values. Since the `receive` macro is not imported by default in R7RS mode (`-r 7`), should the code examples be updated to use `(let-values ...)` instead? That's defined in both R7RS and classic mode.

**Comment by shirok** [comment]
I intentionally use `receive` to promote it.  It's beein in Gauche from the beginning, and been srfi for 20 years, and I prefer it to `let-values`.

**Comment by lassik** [comment]
I agree that `let-values` has too many parentheses but use it anyway because it's in R6RS and R7RS. According to Arthur's counting `receive` is implemented in 21 Schemes, so if you prefer it, let's keep it that way.
