### ISSUE TITLE
warn when user exports an non-existing symbol

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#522]
This is an improvement point. While testing srfi-171 with chibi, I noticed that chibi caught the export symbols (in define-library) that do not really exist. I tested with Gauche first, but it did not complain about this.

Catching non-existent symbols like this may be a good idea (e.g. typos in the export form). But if it's a lot of work, definitely not something to put more time in.

**Comment by shirok** [comment]
In Gauche, such checks are delegated to tests.  Use `test-module` in your tests, which not only checks such dangling exports, but also checks reference to undefined variables, calling procedure with wrong number of argumets, etc.
