### ISSUE TITLE
Documentation of reader-lexical-mode is not updated

### ISSUE THREAD

**Issue by bunder** [shirok/Gauche#552]
Documentation of `reader-lexical-mode` reads:

> Identifiers beginning with a colon are read as keywords, as they’ve always been. For the strict R7RS behavior, you need to use vertical-bar escaping (e.g. |:foo|) to have symbols beginning with colon. Note that this incompatibility will be addressed in the future version of Gauche, when keywords become a subtype of symbols.

It seems it should be updated to reflect that keyword are symbols by default now.

**Comment by shirok** [comment]
Indeed.  Thanks.
