### ISSUE TITLE
Better way of handling .so version (or locating libgauche.so)?

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#556]
Today I ran the test and got this error

```
Testing SRFIs ...                                                failed.
discrepancies found.  Errors are:
test bindings in #<module srfi-14>: expects () => got "symbols exported but not defined: (char-set-hash) AND found dangling autoloads: (char-set-hash)"
test char-set-hash: expects #t => got #<<error> "unbound variable: char-set-hash">
```

but it turns out a false positive because I installed 0.9.9 and 7bbadf4d4 (Moved char-set-hash to core, 2019-12-14) changed libgauche.so, but the one in src/ was not picked up. Instead the outdated version in my installation was used.

This is not the first time I see this problem, I had plenty segfaults before because of gosh using a wrong libgauche.so. Is there any way we can improve this?

The most obvious option is simply set LD_LIBRARY_PATH to prefer src/libgauche.so to the system one. I know LD_LIBRARY_PATH is not available everywhere, so we could just wrap it in a shell script and only set on platforms we know it works.

Another one is keep increasing the gauche version in `AC_INIT` in configure.ac. I think you used to add `_pre<N>` but I'm not sure the rules (and I've seen cases where it's not incremented correctly). So if we have some way to just generate `_preN` that's probably best...

**Comment by shirok** [comment]
Before, there weren't many people who regularly worked on the HEAD, so I let the occasional version mismatch happen; if you notice something weird, update the source and build from clean slate.  After all, only handful of active Gauche developers are affected.  The _preN versioning was based on whenever I felt like, and there was no rule.

However, we might need to do it systematically if the active developer grows (which is a good news!), 

Theoretically, the version number must be updated whenever API change happens (even internally), but there's no way to automatically detect that.  Incrementing it for every commit would be too much.
Furthermore, changing AC_INIT requires running autoconf; doing so after every git pull would be another annoyance.

Automatically including git hash at build time is a possibility.  Though I don't want to make it explicit API.  Currently, Scm_Init() takes the "signature" (including Gauche ABI version plus a couple of options, but that's for applications that links libgauche and not for checking micro-micro-version difference.   If you can come up something that (1) don't interfere with libgauche users, and (2) effective to notify developers the version mismatch, that'll be great.

**Comment by pclouds** [comment]
You didn't say anything about the `LD_LIBRARY_PATH` idea. Is it a "no"? I mean, I think something like this gosh.sh.in (similar to what libtool does, I think) would work

```
#!/bin/sh
LD_LIBRARY_PATH=@topdir@:$LD_LIBRARY_PATH @topdir@/src/gosh "$@"
```

then update Makefile.in to use this instead of gosh directly

Assuming it was a "no"...

> Furthermore, changing AC_INIT requires running autoconf; doing so after every git pull would be another annoyance.

it actually annoys me now :D Can we do something about this too? automake obviously makes it work, perhaps we can just have some make rule like this...

    config.status: configure.ac
        ./DIST gen; ./run-configure-with-the-same-options somehow

Anyway, back to the main topic. How about we use CI to detect ABI breakage? The CI job would

- compile and install latest released tarball
- compile and install last git commit that changes gauche .so version
- compile and 'make test' the new commit

If .so version is supposed to change but did not, I would expect 'make test' to fail (most of the time). This is probably what devs usually do anyway. If it catches an ABI breakage, either you fix up 'master', or people doing PRs will fix the PR and try again.

If it's a good idea but you're busy, I can look into it. But I need to know what CI system you prefer to use.

**Comment by pclouds** [comment]
OK something like this might work (might need to change DIST script a bit though)

```
config.status: configure.ac
    ./DIST gen; ./config.status --recheck

Makefile: Makefile.in
    $(topdir)/config.status $@
```

then any time you update configure.ac or Makefile.in, the configure is automatically run or Makefile recreated.

**Comment by shirok** [comment]
I have bad experiences including dependencies in Makefile that triggers autoconf.  Maybe it's a resolved concern, but autoconf used to introduce incompatibilities between versions, and tended to break when your machine's autoconf version was different from the original developer's.  When you fetch a taraball (that is, it has configure created by the original developer), then you accidentally touch configure.ac (with no intention of changing it), then the hell breaks.

I think it is safe to regenerate Makefile whenever Makefile.in is updated.  Just make sure to use top_buiddir, when you're building out-of-tree.

And I overlooked LD_LIBRARY_PATH part.  You mean to include gosh.sh which runs 'in-place'?  I think it's acceptable, except that it's confusing to have two ways to run in-place (./gosh.sh, or ./gosh -ftest in case the platform doesn't have LD_LIBRARY_PATH; at least old Solaris had LD_RUN_PATH or something).  Any additional layer introduces another possibility of breakage over time, so I'm conservative here, but If you think it improves our life, we can go for it.

**Comment by pclouds** [comment]
It turns out the problem I'm seeing is probably specific to me (or to the very few who set up `LD_LIBRARY_PATH`). The problem is `LD_LIBRARY_PATH` overrides runpath, created by `-rpath`. I'm going to open a PR anyway, I think the change is not that intrusive and maybe it's still ok.

For reference: [ld.so order of search paths](https://en.wikipedia.org/wiki/Rpath#GNU_ld.so) and [the story about rpath and runpath](https://stackoverflow.com/questions/52018092/how-to-set-rpath-and-runpath-with-gcc-ld)
