### ISSUE TITLE
Permission to add SRFI 130 (cursor-based string library)?

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#567]
I was trying to port srfi-159 from chibi to gauche. But most of it was rewriting to avoid srfi-130 and I think this is the reason I got bored and basically stopped for many weeks.

So perhaps we can add srfi-130 to Gauche? That also lets people run a purely scheme regex engine (also from Alex Shinn) if they want to. Maybe not optimized cursors with deep integration to Gauche strings, but at least the compatibility layer is there and maybe later we can start optimizing.

I need to ask this because I think adding an srfi is a sign that Gauche endorses that srfi. And that is definitely not my call.

 - [x] Deal with `<string-pointer>`. Maybe move it to the new cursor.

PS. Kinda unrelated, but I quite like srfi-171 transducers too. May I add it too? :D

**Comment by shirok** [comment]
(...refreshing my memory...) I think the reason that I put off srfi-130 is not that I don't like it, but just that I want to think over what's the best way to support it.  So it's good to bring it back on table.

If Gauche is to have srfi-130, one thing I want to avoid is to have separate procedures with the same name as existing ones, e.g. having separate srfi-13#string-every and srfi-130#string-every.  I just want one string-every that can handle both cursor and index.  This should extend to every procedures that accept string indexes, so the task is rather daunting, which is why I put it off, now I remember...

We don't need to change everything at once.  I'm fine just to cover srfi-130 procedures at at starting point and gradually enhance cursor support to other string procedures.  But we do need to have a prospect that such enhancement be easy and consistent.  At the moment I'm open to the actual representation of cursors.  Feel free to put your ideas here.

**Comment by pclouds** [comment]
Yuck. I should have given it more thought than "hey let's add this". My initial idea was just a cons of a string and a number as cursor, won't be as fast as a C pointer (with boundaries), but could be done entirely in Scheme.

But I have a homework to do now. I'll need to study the state of string handling in Gauche and srfi-130 more closely and come back. Thanks for the reply. At least this looks more fun!

**Comment by shirok** [comment]
If we can make it opaque without much overhead it'd be better, for users won't accidentally break it, but `(cons <string> <integer>)` is a good starting point.  Some string procedures are defined in cproc, so we need common utilities both in C and Scheme that universally handles index-or-cursor arguments.

There's an internal procedure `%maybe-substring` in libstr.scm that handles optional start/end arguments.  For Scheme part, making it accept cursors would make many Scheme procedures that takes optional start/end arguments automatically accepts cursors.

**Comment by pclouds** [comment]
Let's go with a disjoint type from the beginning because it does not look hard to do

```
struct ScmStringCursorRec {
    SCM_HEADER;
    const char *cursor;
    // or ScmSmallInt index; ??
};
```

The caller has to provide a string object "str" separately, we can easily validate if "cursor" is within str->body.

There should not be any multithread issues with this right? As long as we keep a copy of `SCM_STRING_BODY(str)` call at the beginning of some function and keep using that pointer.

Yeah updating `%maybe-substring` would enable a lot of procedures to use cursors. Some procedures need to stay with indexes though (e.g. `substring` from r7rs does, `substring/cursors` is provided by srfi-130)

**Comment by pclouds** [comment]
Actually ignore the "or ScmSmallnt" comment. That would work if I kept ScmString pointer in here to prevent the garbage collector to remove the string. But with "index" field alone, no such guarantee.

**Comment by shirok** [comment]
We can enhance substring to allow cursors (liberal interpretation of 'error') and just make substring/cursors an alias substring.  Can't we?

**Comment by shirok** [comment]
And you're right.  ScmStringBody is immutable and you don't need a lock once you get hold of it.

**Comment by pclouds** [comment]
How do you want to handle this?

string-index returns an index or #f in srfi-13. It returns a cursor in srfi-130.

We can't determine the output type based on input (string-index in srfi-130 can take either index or cursor), they have to be separate implementations. However it's possible to have just one implementation and the other string-index a wrapper that just converts the result type.

I think I prefer to implement cursor-based string-index, then make srfi-13 use it and convert cursor to index (the srfi-13 uses \<string-pointer> that you want to get rid of too). However this introduces a fun dependency between the two because most of the procedures can be shared between them, and most of them are in srfi-13, so srfi-130 depends on srfi-13. And now we make srfi-13 depend on srfi-130.

I guess we could move all the string procedures to something like gauche.string, then make srfi-13, 130 and 152 reexport them. But maybe there's a better way?

**Comment by pclouds** [comment]
Never mind. I see srfi-152 already uses unexported procedures from 13. I can do the same.

**Comment by pclouds** [comment]
I think srfi-130 is basically done at this point (and with _most_ of srfi-159 tests passing it's probably in pretty good shape).

There will be ongoing work to add support for cursors for "the rest" of the procedures where reasonable, and optimization to avoid function calls for optional start/end arguments, but I think we can do that without keeping this one open. That's more about general cursor support anyway.

So I'm closing this one, feel free to reopen it if we should keep track of more things with it.
