### ISSUE TITLE
optional arguments in cgen's define-cptr are not effective

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#59]
I have a declaration like this

    (define-cptr <git-repository> "git_repository*" "Git_RepositoryClass"
      "GIT_REPOP" "GIT_REPO" "GIT_REPO_VALUE"
      :print repo-print
      :cleanup repo-cleanup)

but the generated code is

    Git_RepositoryClass = Scm_MakeForeignPointerClass(Scm_CurrentModule(),"<git-repository>", NULL, NULL, 0);

cleanup-proc and print-proc are not passed to that call. Adding #?= at line 1665 in cgen/stub.scm i got

    #?="/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/stub.scm":1665:(assq-ref clauses 'print)
    #?-    #f

**Comment by shirok** [comment]
Try 

    (define-cptr <git-repository> "git_repository*" "Git_RepositoryClass"
      "GIT_REPOP" "GIT_REPO" "GIT_REPO_VALUE"
      (print repo-print)
      (cleanup repo-cleanup))

**Comment by pclouds** [comment]
That seems to work. Thank you. I mistook it for keyword syntax. define-cptr should probably error out on unrecognized arguments though.

**Comment by shirok** [comment]
That's reasonable.
