### ISSUE TITLE
cond-expand without else clause

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#593]
It seems cond-expand always requires else clause

```
gosh$ (cond-expand (foo 1))
*** ERROR: Unfulfilled cond-expand: ()
    While compiling "(input string port)" at line 1: (cond-expand (foo 1))
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "/home/pclouds/opt/gauche/share/gauche-0.97/0.9.9/lib/gauche/interactive.scm":267
gosh$ (cond-expand (foo 1) (else 1))
1
gosh$ 
```

R7RS states

>  If  none  of  the〈feature requirement〉s  evaluate  to#t,  then  if  there  is  anelse clause, its〈expression〉s are included.  Otherwise, thebehavior of thecond-expandis unspecified. 

So Gauche _can_ do whatever it wants in this case. But it seems throwing an error may be a bit too strong?

I don't see forcing people write `(else)` is a good practice. I do see catching unhandled cond-expand is good when you port a program to a new scheme, but it's probably should be opt-in (and maybe as a warning) instead of mandatory.

**Comment by lassik** [comment]
Gambit and Sagittarius also raise that error. Chibi just returns `#t`.

If my reading of [SRFI 0](https://srfi.schemers.org/srfi-0/srfi-0.html) is correct, it says the error must be raised. The sample implementation raises it. While R7RS cond-expand is subtly different from SRFI 0 cond-expand, uniformity makes it easier to understand. Gauche also has its native, pre-R7RS mode.

FWIW, I like the error. `cond-expand` is like the `#ifdef` of Scheme - the easiest way to turn a perfectly readable program into an unreadable mess :) Hence caution is good. But this is just based on my experience. Hopefully we can soon produce enough portable Scheme libraries and SRFIs that `cond-expand` is needed less often.

**Comment by lassik** [comment]
Here's the quote from SRFI 0:

> It either expands into the body of one of its clauses or signals an error during syntactic processing.

**Comment by pclouds** [comment]
Hmm.. I checked srfi-0 too but only read until this

> the else clause, **if present**, is selected if none of the previous clauses is selected

I don't really have strong opinion about this. Just something strange I found while doing stuff. Feel free to close and keep current behavior.

**Comment by pclouds** [comment]
> Gambit and Sagittarius also raise that error. Chibi and Cyclone return #t. Kawa returns no values.

This is not really democracy, but since I have a few schemes around... Guile is on Gauche side. Larceny and Gerbil with Chibi (yeah I didn't realize you mentioned Gambit until I already tested Gerbil). I also have a suspicion that Sagittarius shares some code with Gauche (but maybe only the beginning?)

**Comment by lassik** [comment]
A significant part of the code in many Scheme implementations is copy-pasted and then hacked from another implementation or library :) That's very good, but the lineage (what came from where) is not always recorded clearly.

So we have so far:

* Chibi -- #t
* Cyclone -- #t
* Gambit -- error
* Gauche -- error
* Gerbil -- no values
* Guile -- error
* Kawa -- no values
* Larceny -- no values
* Sagittarius -- error

Almost a draw.

**Comment by shirok** [comment]
Gauche's behavior is from srfi-0.  It is a bit of annoyance, but I don't see it strong enough to break the precedence.  But the error message can be improved.

**Comment by pclouds** [comment]
Yeah the error message could be a bit better, although it's not hard to find out the problem once the cond-expand in question is identified. I'll leave it for you to close this issue whenever you want.

**Comment by lassik** [comment]
> Yeah the error message could be a bit better

How about `cond-expand has no matching clause and no 'else' clause`?

**Comment by shirok** [comment]
I'd consider no-else cond-expand the same as something like this:

```
#if SUCH_FEATURE
...
#elif ALTERNATIVE_FEATURE
...
#else  
#error "Such feature or alternative feature required"
#endif 
```

So, "feature such and such is required to load this code" may be a good one.  Especially helpful when a non-expert user just downloaded a code from github and tried it.  "Unfulfilled cond-expand" or "cond-expand has no else clause" will give an incorrect impression is that it's a bug in the code.

**Comment by lassik** [comment]
You're right that it's ideal. But there are some quite complicated cond-expand's in the wild (including in my own code) so it may not be easy to summarize the wanted features in an error message.

**Comment by Hamayama** [comment]
I have a similar experience.

I added `cond-expand` to some program without `else` clause.

```
(cond-expand (gauche.os.windows ...))
```

I wanted the program to work on Windows as same as other os.

But, it becames to work on only Windows.
(it raised error on all other os!)

I didn't aware this because it works on my pc (OS:Windows).

If this is spec of srfi-0, it might be useful to warn `Missing 'else' clause`
even if other clause is selected.
(But, it might loss perfomance ...)

**Comment by pclouds** [comment]
> If this is spec of srfi-0

I checked again because I wanted to see if we could improve documents a bit (even if the problems hit people who didn't seem to read it, namely you and I :D) But coresyn.texi does say this

```
@c EN
If there's neither a satisfying clause nor @code{else} clause,
@code{cond-expand} form throws an error.  It is to detect the case early
that the platform doesn't have required features.   If the feature
you're testing is optional, that is, your program works without the
feature as well, add empty @code{else} clause as follows.
@c JP
条件を満たす節も@code{else}節も無かった場合、@code{cond-expand}は
エラーを通知します。この仕様は、
必要な機能を欠いている実行環境を早めに検出するためです。
もしチェックする機能がオプショナル、つまりそれが無くてもプログラムの実行自体は
可能であるというものであるなら、最後に空の@code{else}節を忘れないようにしてください。
```

**Comment by pclouds** [comment]
> So, "feature such and such is required to load this code" may be a good one. Especially helpful when a non-expert user just downloaded a code from github and tried it. 

#614 

> If this is spec of srfi-0, it might be useful to warn Missing 'else' clause
even if other clause is selected.

I wanted to do something about this too but I found no good way to do this.

For new code, a warning definitely helps. However if you run imported code that has cond-expand without else clauses, the warning gets annoying fast.

And making the warning optional is not helping because we want to help people who do not know about this behavior (and the switch to turn the warning on)...

**Comment by pclouds** [comment]
Closing this as I don't think there's any more we can do about it. Feel free to reopen.
