### ISSUE TITLE
Maybe I should make #?= to insert the hygienic identifier instead of a literal symbol

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#597]
for context see #583 which was accidentally closed by me. Reopen an issue here to keep track.

**Comment by shirok** [comment]
Reader macros generally insert bare symbols. Make it insert identifier could have unexpected consequences.  I vaguely remember I once tripped over it but forgot the details.  That's what's bugging me.

Well, you can go ahead and let's see if it causes any problems.

**Comment by pclouds** [comment]
No no I'm not touching "identifier" stuff especially when hygiene is related! I'm nowhere close to understand all that stuff. Let's close this. It's a minor thing anyway.
