### ISSUE TITLE
Unicode classification problem.

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#598]
Maybe a problem. Maybe not. This is from Chibi 115 test suite

```
$ ((#/[[:LOWER:]]*/ "σζǅ") 0)
"σζ"
```

The last letter is 0x1c5 "LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON". It's kinda confusing, I guess, because it's both "capital" and "small".

Chibi matches all three here. I'm no expert to judge if Chibi or Gauche is right.

**Comment by shirok** [comment]
According to the Unicode Character Database, U+01c5 is category Lt (Letter, titlecase).  We only treat category Ll (Letter, lowercase) as [[:LOWER:]]. We can ask Alex what properties Chibi treats as lowercase.

**Comment by pclouds** [comment]
Sorry false alarm. Chibi does treat U+01c5 the same way. The problem I had was with SRE `(w/nocase (* lower))` but I lost track and kept testing the lower part instead. Will leave this one open though while I figure out why Gauche w/nocase and Chibi's does not behave the same way...

**Comment by pclouds** [comment]
Closing. Very likely bug in sre.scm
