### ISSUE TITLE
SRFI 176 Scheme library

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#610]
The final version of SRFI 176 specifies that the information in the -V output should also be accessible from Scheme code (at the request of John Cowan, which I though a good idea). It's specified in the [Accessing from Scheme](https://srfi.schemers.org/srfi-176/srfi-176.html#_accessing_from_scheme) section.

Implementation can be as simple as adding something like:

```scheme
(define-module srfi-176 (export version-alist))
(select-module srfi-176)

(define (version-alist)
  `((version ,"...")
    (command "gosh")
    (scheme.id gauche)
    (languages scheme r5rs r7rs)
    (encodings ,@(|...|))
    (website "https://practical-scheme.net/gauche")
    (build.platform ,"...")
    (scheme.path ,@("..."))))
```

filled in with the right calls to get the info.

**Comment by lassik** [comment]
Another option is constructing that alist in a C function and having `version()` in `main.c` call the Scheme printer to write the same alist as the `-V` output.

**Comment by pclouds** [comment]
This is the part I find questionable. What is it used for? You can already cond-expand based on scheme.id (or id+version). languages are irrelevant unless you try to write in r5rs with optional features in r7rs. All other settings, I see no use case except maybe reporting bugs, but then just run "\<scheme> -V" would be as good.

**Comment by lassik** [comment]
John thought of withdrawing SRFI 112 (Environment Inquiry) in favor of 176 since the latter can provide the same information and more to Scheme programs. While all the info in 176 can be obtained in other ways, 176 provides it in a standard form. While an alist is not an ideal Scheme-side API, it's possible to share its implementation with the -V flag.

**Comment by lassik** [comment]
To anticipate situations like this, I wrote the 176 spec in such a way that it's legal for `(version-alist)` to return different information than the `-V` flag; even returning an empty list from `(version-alist)` is a valid implementation.

**Comment by pclouds** [comment]
So this _is_ about reporting. Thanks that answers my question.

**Comment by lassik** [comment]
Yeah, it's probably mostly useful for displaying info to humans. Either querying it from the REPL, or if a program wants to display something like `Running in {scheme.id} {version}` to the user, `(version-alist)` is a natural place to get those strings. Programs could do things like groveling `scheme.path` to look for files, but they probably shouldn't.

**Comment by shirok** [comment]
Thanks for pointing this out.  I added version-alist and main.c calls it to create -V output.

**Comment by lassik** [comment]
Perfect, thanks!

In R7RS mode `version-alist` should also be importable from a `(srfi 176)` library.

**Comment by lassik** [comment]
Ref 2c9de60

After a `./DIST gen`, `./configure`, `make && make install`, everything works. The implementation is beautifully concise. Thank you very much Shiro for being the first implementor of the SRFI :)
