### ISSUE TITLE
Better error reporting on invalid cise forms

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#62]
I got this invalid define-cfn because return value needs to be wrapped in ()

    (define-cfn GIT_INDEX_ENTRY_VALUE (obj) ::const git_index_entry* :static
      (return (Scm_ForeignPointerRef (SCM_FOREIGN_POINTER obj))))

and "gauche-package compile" gives me the below error message. What I need is the location of this incorrect form so I can examine and correct it. But I don't see the location is printed anywhere.It's quite hard to track down this form manually.

    "/home/pclouds/opt/gauche/bin/gauche-package" compile --libs -lgit2 --cflags "-Wall -Wno-unused-label -Wno-unused-but-set-variable" \
      --local="/tmp/libgit2" --verbose libgit2 ./libgit2.c ./libgit2lib.stub
    *** ERROR: Invalid CISE form:  :static
    Stack Trace:
    _______________________________________
      0  (map (cut render-rec <> env) (cdr form))
            At line 574 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      1  (expander form env)
            At line 350 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      2  (render-rec (expander form env) env)
            At line 350 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      3  (render-rec form env)
            At line 302 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      4  (cise-render-to-string `(begin ,@body) 'stmt)
            At line 454 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      5  (expander form env)
            At line 350 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      6  (render-rec (expander form env) env)
            At line 350 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      7  (render-rec form env)
            At line 302 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/cise.scm"
      8  (cise-render-to-string `(define-cfn ,@args) 'toplevel)
            At line 323 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/stub.scm"
      9  (cgen-stub-parse-form form)
            At line 258 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/stub.scm"
     10  (fn item r)
            At line 242 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/procedure.scm"
     11  (with-input-from-file stubfile (cut generator-fold (^ (form decl-s
            At line 252 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/cgen/stub.scm"
     12  (cgen-genstub file)
            At line 84 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/package/compile.scm"
     13  (with-error-handler (lambda (e) (exit-handler x) (h) (raise e)) (l
            [unknown location]
     14  (apply gauche-package-compile src (delete-keyword :output args))
            At line 122 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/package/compile.scm"
     15  (map (lambda (src) (cond ((equal? (path-extension src) OBJEXT) src
            At line 119 of "/home/pclouds/opt/gauche/share/gauche-0.9/0.9.5_pre1/lib/gauche/package/compile.scm"
     16  (with-error-handler (lambda (e) (let ((e e)) (%guard-rec e e (else
            [unknown location]
     17  (x (cddr args))
            [unknown location]
    make: *** [libgit2.so] L?i 70

**Comment by shirok** [comment]
We're planning to phase out genstub and eventually move to precomp.  If it were precomp, you'd better source location infroamtion:

    $ ./gosh -ftest precomp t.scm
    Error in compiling (inline-stub (define-cfn GIT_INDEX_ENTRY_VALUE (obj) ::const git_index_entry* :static (return (Scm_ForeignPointerRef (SCM_FOREIGN_POINTER obj)))))
    *** ERROR: Invalid CISE form:  :static
        While compiling "t.scm" at line 1: (inline-stub (define-cfn GIT_INDEX_ENTRY_VALUE (obj) ::const git_index_entry* :static (return (Scm_Fo ...

Some of the toolchains still use genstub, so it may be a good idea to improve genstub as well for the time being.

**Comment by pclouds** [comment]
Ah.. then it's probably not worth doing anything in this area unless it does not cost much time. I'll see if I can make 'gauche-package compile' optionally use precomp, but success chances are slim :-D

**Comment by shirok** [comment]
I guess just duct-taping genstub will provide immediate benefit in this case.  Let me look at it.

**Comment by shirok** [comment]
Actually it was just a small tweak to allow genstub to report the source location.  Fix pushed.
