### ISSUE TITLE
srfi-105 implementation

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#628]
b5b02bbed88eb8740e5be40cd135e16209a76905 added a small amount of code for srfi-105 but at that point in time the srfi was probably not finalized. The srfi is long done now. This issue is to keep track of it. If it's decided we don't want the srfi, we could remove the old code. Otherwise, lots of work to do...

**Comment by shirok** [comment]
Good catch.  I think I added it to experiment the srfi back then.  It's mildly interesting to support it but doesn't seem to worth to be in the core.  I'd rather have it supported with pure-Scheme library via reader-directive hook.   So yeah, I'm for removing it.

**Comment by pclouds** [comment]
No problem. Please do and close this one. It's done its job (catching your attention)
