### ISSUE TITLE
documentation about gosh -f and -p not uptodate

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#63]
It looks like there are a lot more options implemented in further_options() than documented, even not counting those "for development, not for public use". gauche-ref.texi and gosh.1.in both may need updates.

As for -p, -pload is not documented in gosh.1.in and profiler_options() should print "supported profiling options are: -ptime or -pload" instead of just "..options are: -ptime"

**Comment by shirok** [comment]
Thanks, update pushed.  Let me know when you notice other discrepancies.
