### ISSUE TITLE
run-process: support splitting arguments on windows

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#65]
I don't use windows. THis is just an observation. The comment about Windows before %apply-run-process was added in 535614b (further windows support - 2007-09-18). Three years later you added arg split support, but for "run" procedure in gauche.package.util,  in 249d4fd (fix gauche-package on windows - 2010-11-21).

I suppose the split code is good enough to be migrated to run-process, you just forgot about run-process when you added it.

**Comment by shirok** [comment]
Good catch.  I certainly forgot about %apply-run-process thing.  However, when the high-level process API (such as call-with-input-process) takes a string, it allows shell metaprocessing (e.g. you can pass commands chained with pipes), so simply using win-break-cmdargs won't do.

Integration of those two is certainly a future option.  Personally I'm tired of working around defects of Windows console and command interface, and am inclined to implement a sane shell feature (including redirection and piping) within Gauche.
