### ISSUE TITLE
process-output->string-list doesn't accept keyword :encoding

### ISSUE THREAD

**Issue by actorbug** [shirok/Gauche#651]
process-output->string-list で :encoding キーワードは使えなくなったのでしょうか。
0.9.4 では使えていたと思うのですが、0.9.9 だと以下のエラーになります。

gosh> (process-output->string-list '(ls) :encoding 'shift_jis)
*** ERROR: unknown keyword :encoding
Stack Trace:
_______________________________________
  0  (errorf "unknown keyword ~S" (car #:args88))
        [unknown location]
  1  (%apply-run-process command input :pipe err host rest)
        at "../lib/gauche/process.scm":593
  2  (eval expr env)
        at "../lib/gauche/interactive.scm":269

**Comment by pclouds** [comment]
That's probably dbcdc3ecb034caf2bc2041126da9defd7622e0d8. The remaining keywords "rest" are now passed in both %apply-run-process and wrap-output-process. The latter accepts :encoding, but the former already rejects it.

**Comment by shirok** [comment]
You're right, @pclouds .

**Comment by shirok** [comment]
このfixでどうですか。

**Comment by actorbug** [comment]
動きました。早々に対応していただき、ありがとうございました。
