### ISSUE TITLE
Coding style for Gauche

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#658]
I notice that scheme code in Gauche does not exactly follow standard scheme indentation rules in Emacs. So perhaps we should add a small `.emacs` snippet Shiro is using in the repo so others can reuse (and mentioned in HACKING.adoc so people know where to look)

Yes it's very emacs-specific but it's probably good enough for now. I'm aware of https://practical-scheme.net/wiliki/wiliki.cgi?Gauche%3AEditingWithEmacs but I don't think that's what's being used (the custom `if` indentation is not there).

The same could be said for C coding style as well. It's probably one or two lines of emacs settings... But there's subtle things like, this style seems to be encouraged

    if (something) return somevalue;

**Comment by lassik** [comment]
For the C coding, I highly recommend an auto-formatter. In particular, `clang-format` is excellent.

For Scheme, the SRFI community should codify a standard Scheme coding style. This is easier to do for Scheme than for almost any other language. We have no tabs-vs-spaces, indent width, brace style or operator precedence debates.

**Comment by lassik** [comment]
For `clang-format`, `whatstyle` can find decent settings automatically by analyzing existing code. https://github.com/mikr/whatstyle

**Comment by lassik** [comment]
An `.editorconfig` can make Emacs/Vim/Visual Studio settings match the auto-formatter style. https://editorconfig.org

**Comment by lassik** [comment]
If we specify a standard style for Scheme, we can send patches to the GNU Emacs `scheme-mode` so that future versions of Emacs automatically have the right indentation.

**Comment by pclouds** [comment]
To be honest I wasn't aiming for standardizing coding styles for al schemes. The first differences in Gauche is `if` is indented as a special form, not as a procedure call. That's already debatable trying to change that in stock emacs.

The change in `if` form is meant for gauche developers only, to keep consistent style in the code base. Gauche users can just use standard rules.

Then there are custom gauche forms that, without new rules, will be reformatted as procedure calls. These definitely can't be upstreamed to emacs. Having them in the repo makes it easier to look for them (even by Gauche uesrs), and hopefully  keep them from rotten.

**Comment by lassik** [comment]
Since we have macros to define custom syntax, the same problem occurs with all Scheme and Lisp code. We should invent a standard convention for communicating custom Lisp indentation to editors and auto-formatters.

Gauche's idiosyncratic indentation of `if` could be handled using that same mechanism. It could just say that `if` is indented the same way that `when` is indented.

**Comment by lassik** [comment]
Perhaps we should have a `.scheme` file where to put this and other metadata for a project. I have some ideas...

**Comment by pclouds** [comment]
The autoformatter I have in mind is emacs, and the mechanism to change indentation already exists. What's needed is info from Gauche. I can't say about editorconfig and frankly don't care that much.

**Comment by lassik** [comment]
Yeah, `(put ... 'scheme-indent-function ...)` already works. The standard convention would just hook it up to some metadata file where the custom indentation is configured.

editorconfig is super simple to set up and works with lots of editors. For Emacs, http://melpa.org/#/?q=editorconfig (200k downloads)

**Comment by shirok** [comment]
I haven't been a big fan of standardizing coding style too much, but it is certainly convenient if others can just load my style.   I think the snippet in WiLiKi is somewhat outdated.   I'll add my current one somewhere in the source as a sample.

Recently I write go and gofmt did affect my perception about autoformatting.  I might  try out the tools @lassik suggested.

**Comment by lassik** [comment]
To solve the immediate problem with Emacs, something like this would work:

```emacs lisp
(defun gauche-scheme-style ()
  (interactive)
  (put 'and-let* 'scheme-indent-function 1)
  (put 'begin0 'scheme-indent-function 0)
  ...)

(defun gauche-scheme-style-hook ()
  (when (and (buffer-file-name)
             (let ((dir (file-name-directory (buffer-file-name))))
               (save-match-data
                 (let ((case-fold-search t))
                   (string-match "gauche" dir)))))
    (gauche-scheme-style)))

(add-hook 'scheme-mode-hook 'gauche-scheme-style-hook)
```

I just realized that properties altered with `put` are not buffer-local, so changing the `scheme-indent-function`s will probably change them for all your Scheme buffers. Emacs may not have an easy way to fix that.

**Comment by pclouds** [comment]
> I just realized that properties altered with put are not buffer-local, so changing the scheme-indent-functions will probably change them for all your Scheme buffers. Emacs may not have an easy way to fix that.

I think it can be fixed by creating a new mode inheriting scheme-mode. But in practice I don't think this is a problem. I assume most Gauche users rarely switch Schemes for it to become a real problem.

**Comment by lassik** [comment]
That won't work because Lisp indentation settings are fundanemtally done via symbol properties (or function properties). They are always global to all of Emacs (except when lexically bound as a hack).

I wrote an Emacs package as a workaround to solve the problem: https://github.com/melpa/melpa/pull/6812 Hopefully it will be available from MELPA soon.

**Comment by lassik** [comment]
The package, called `lisp-local`, is now installable from MELPA: http://melpa.org/#/lisp-local

**Comment by pclouds** [comment]
Shiro updated .dir-locals.el. I guess we can close this now.
