### ISSUE TITLE
Saving the configure command line for run time

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#660]
Would there be an easy way to save the command line given to `./configure` into the Gauche executable? It's useful in replicating the build later if the binary can tell the exact settings it was built with.

**Comment by lassik** [comment]
Maybe these would be useful to save as well:

```

This Gauche has been configured with the following parameters:
           [...]
              slib: /usr/local/slib
           tls/ssl: axtls 
          CA store: none 
  optional modules: ndbm gdbm zlib
```

You probably have all the right information in the binary already.

SRFI 176 has a standard field `build.configure` for the command line, but no standard fields for the other things listed above. It is possible to add custom fields, for example `gauche.slib`, `gauche.tls`, `gauche.ca-store`, `gauche.modules`.

**Comment by shirok** [comment]
From a program, you can access it with gauhce.config module.

```
gosh> ,u gauche.config
gosh> (gauche-config "--reconfigure")
"./configure  '--prefix=/usr' '--enable-multibyte=utf-8'"
```

From a shell, `gauche-config --reconfigure` command does.
