### ISSUE TITLE
Support --help in `gauche.parseopt`

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#661]
One of the things I found lacking when I used gauche.parseopt. `make-option-parser` already has enough information to print the whole command syntax, but we still have to do it manually.

It would be great if we could tell gauche.parseopt to handle `--help` option somehow. It could print the basic command options (and their help strings), and the user could provide a bit more description of the command in general.

I have not really worked it out though. So I don't know if it's possible to do and what kind of interface we provide to do it. Obviously hard coding recognizing `--help` in gauche.parseopt is not the way to go...

**Comment by shirok** [comment]
It's on my todo list for long time.

Originally we had `make-option-parser`, `build-option-parser` and `parse-options`.  Then Alex introduced `let-args` on top of them, and that's so convenient that I use `let-args` exclusively these days.

If we are to add automatic help generator, the effect propagates to these middle layers too.  But my hunch is that we'd better forget the middle layer and optimize `let-args` to do fancy staff.  We can also use er-macro now, which may simplify `let-args-internal` recursion.

**Comment by shirok** [comment]
Finally got around with this.  See `gauche-install.in` for the example of usage.  Documentation will follow.

The syntax `? <help-string>` may be debatable.  Needed a marker to distinguish help string from default value.  We could've make default value mandatory when help string is provided, but I think it is error-prone.

**Comment by shirok** [comment]
Closing.
