### ISSUE TITLE
alist->hash-table in (srfi 125) is not compatible with specification

### ISSUE THREAD

**Issue by mnieper** [shirok/Gauche#662]
Gauche's `alist->hash-table` from `(srfi 125)` does not follow the specification. In SRFI 125, the first argument is an alist, the second argument is a comparator or equality procedure.

**Comment by shirok** [comment]
Right.  Gauche's built-in `alist->hash-table` has the same order as srfi-125, and I have a separate code specifically changing the argument order in srfi-125 module, so I may have misunderstood the spec.

**Comment by shirok** [comment]
Shuold be fixed.

**Comment by shirok** [comment]
Closing.
