### ISSUE TITLE
handle Ctrl-C in gosh prompt

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#672]
From gosh prompt, type acacbabc\<ctrl-c> we got

```
gosh$  acacbabc*** UNHANDLED-SIGNAL-ERROR: unhandled signal 2 (SIGINT)
Stack Trace:
_______________________________________
  0  (read-char (~ con 'iport))
        at "/home/pclouds/opt/gauche/share/gauche-0.97/0.9.9/lib/text/console/generic.scm":240
  1  (getch con)
        at "/home/pclouds/opt/gauche/share/gauche-0.97/0.9.9/lib/text/line-edit.scm":246
  2  (read-line/edit ctx)
        at "/home/pclouds/opt/gauche/share/gauche-0.97/0.9.9/lib/gauche/interactive/editable-reader.scm":67
  3  (read)
        at "/home/pclouds/opt/gauche/share/gauche-0.97/0.9.9/lib/gauche/interactive.scm":238
gosh$ 
```

The outcome (clearing current command) is good. But we probably don't have to print all that "unhandled signal error". We probably can catch this exception while in edit mode and remove it before evaluating any expression.

**Comment by shirok** [comment]
Added `guard`.

**Comment by pclouds** [comment]
Verified.

Here's a corner case: pressing ctrl-c twice. The second time, there's technically no input to interrupt from. But I don't think we need to do anything about that.
