### ISSUE TITLE
PAGER=cat does not show line-edit keybindings as expected.

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#688]
Very nice `C-x h b` ! It does not seem to work well with PAGER=cat though, but perhaps this is the kind of corner cases that's not worth suppoting?

To reproduce, do `C-l` to clear the screen first so the prompt is at the top. Then `C-x h b` shows nothing. If the prompt is just a few lines down then we can see the top part of the keybindings before the prompt

I think PAGER=dumb does not work either. I expected it to just dump the whole keybindings out when there's no pager....

**Comment by shirok** [comment]
Okay, it does dump the info, but the screen is immediately reset by the next prompt.
Maybe we could re-query the cursor pos after pager process.  Let me see...

**Comment by lassik** [comment]
Most real pagers and editors nowadays draw on the alternate screen but I'm not sure whether that's universal.

**Comment by shirok** [comment]
`PAGER=cat` is a valid use case, for `text.pager` is also used to display online document.

**Comment by lassik** [comment]
Would it work if Gauche never cleared the screen unless the user explicitly presses Control-L? The alt-screen programs generally restore the terminal the way it was, which means they should leave Gauche's REPL intact.

**Comment by shirok** [comment]
Gauche's REPL is intact.  That's not the problem.
In case of `less`, the pager pauses at the end of display, and once quit, it restores the display.  In case of `PAGER=cat`, Gauche restores the terminal state as soon as cat show the content.  If it is during line-editing, restoring means the cursor goes back to the position at the time last read has started, and whatever buffer content is redrawn after it.   The content displayed by cat is either overwritten or scrolled away.

**Comment by shirok** [comment]
`PAGER=cat` should work now.
Is `PAGER=dumb` common?  I suppose `PAGER` contains a command line to invoke, so it'll try to call a program `dumb`...

**Comment by pclouds** [comment]
I tried `dumb` because it was explicitly checked in `pager-unavailable?` So maybe line-edit should call that and fallback to display if no suitable pager is available.

PS. Yes `PAGER=cat` works now. Gauche's one step closer to replacing Emacs, muahahaha

**Comment by shirok** [comment]
Oh, that part of `pager-unavailable?` is checking `TERM`.  `TERM=dumb` is a common way to tell the program that the terminal is, well, dumb.

**Comment by pclouds** [comment]
Right I knew about the TERM=dumb convention but forgot that by setting it, line-edit is already out of the window, and worse somehow mixed up `$TERM` with `$PAGER`!
