### ISSUE TITLE
line-edit: C-x h k changes background color?

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#689]
Not sure if it's intentional, but it looks a bit weird that the key description is in reversed background. See here

https://i.imgur.com/rUSH5Ba.png

**Comment by shirok** [comment]
I'm kind of trying out options.  It does seem a bit too much.  You can also experiment by changing the last argument of `show-message` in L1105.

**Comment by pclouds** [comment]
`bright` works better for me.  Underlining probably works too if we avoid underlining the white spaces between columns. Changing foreground color would work, but I think we'll just have to let the user customize the color, no one color works for everybody.

**Comment by shirok** [comment]
Hm, yeah, bright looks better.  How about the `undefined-command`? Currently I'm using reverse there to guide the user to help.

**Comment by pclouds** [comment]
I think that's actually a good use. It definitely catches my attention.

About reversed background, I think my biggest problem is with the shape of the white background. If it looks more like a rectangle, then it would still work.

**Comment by shirok** [comment]
Ah, right.  That makes sense.
