### ISSUE TITLE
case-lambda in r7rs library doesn't work

### ISSUE THREAD

**Issue by jgonis** [shirok/Gauche#701]
Hi there,

I have a simple test case using gauche 0.99 and trying to get case-lambda to work.

```
(define-library (libs test-example)
  (export f)
  (import (scheme base))
  (begin
    (define f
      (case-lambda
        [() 'zero]
        [(a) `(one ,a)]
        [(a b) `(two ,a ,b)]))))
```

I took this directly from the manual section on case lambda.  Running at the repl, and trying to load it results in the following error:
```
gosh[r7rs.user]> (load "libs/test-example.scm")
*** ERROR: invalid application: (() zero)
    While loading "file location on my pc" at line 9
Stack Trace:
_______________________________________
  0  (() 'zero)
        at "file location on my pc/test-example.scm":7
  1  (case-lambda (() 'zero) ((a) `(one ,a)) ((a b) `(two ,a ,b)))
        at "file location on my pc/test-example.scm":6
  2  (eval expr env)
        at "c:\\Program Files\\Gauche\\share\\gauche-0.97\\0.9.9\\lib/gauche/interactive.scm":269
```

Using `(import ...)` results in the same error as does `(include ...)`

Thanks again for all your hard work on Gauche, I really enjoy using it!

**Comment by jgonis** [comment]
I see now that r7rs requires you to import the `(scheme case-lambda)` library in order to use the construct. My apologies for the mistake.

**Comment by shirok** [comment]
You found the answer.  Note that we're aware that the error message in these cases (when you forgot to import a macro) is perplexing, and trying to improve it.  If it said "I don't know 'case-lambda'", it would've been easier to spot the problem.
