### ISSUE TITLE
:optional does not work in R7RS mode

### ISSUE THREAD

**Issue by ar-nelson** [shirok/Gauche#706]
A definition with `:optional` arguments, like this:

```
$ gosh
gosh> (define (foo a :optional (b 1) (c 2)) (+ a b c))
foo
gosh> (foo 2 3)
7
```

does not work when running `gosh` in R7RS mode:

```
$ gosh -r7
gosh[r7rs.user]> (define (foo a :optional (b 1) (c 2)) (+ a b c))
*** ERROR: proper list required for function application or macro use: ((b 1) (c 2) . #:G176)
    While compiling "(standard input)" at line 1: (define (foo a :optional (b 1) (c 2)) (+ a b c))
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "/usr/share/gauche-0.9/0.9.6/lib/gauche/interactive.scm":267
```

I'm aware that this is probably intentional, because `:optional` is a Gauche extension, and not valid R7RS. However, if the goal is to be fully compliant with R7RS, it should accept `:optional` as a parameter name (not a keyword), at least when in `GAUCHE_KEYWORD_IS_SYMBOL` mode.

Alternately, if `:optional` is not a valid parameter name in R7RS mode, it should at least display a more informative error message.

There should also be a way to explicitly import Gauche's `define` behavior in R7RS. While a fix in a future Gauche version would be nice, I'm also interested in a workaround for this in Gauche 0.9.6. I'm implementing a portable `define+` macro in [Schemepunk](https://github.com/ar-nelson/schemepunk) that supports `:optional` and `:rest` syntax, and would like to use each Scheme's native optional-parameters implementation. (For performance. Although I don't know if Gauche `:optional` actually has a performance advantage over `case-lambda`.)

Importing `(gauche base)` seems to make `:optional` work in the REPL, but this doesn't work inside an R7RS library. I thought that `(import (only (gauche base) define))` would work, but that doesn't do anything in the REPL or in a library. Is there anything I can import from `gauche`, or exclude from `(scheme base)`, to make `:optional` work inside an R7RS `define-library` form?

**Comment by shirok** [comment]
In R7RS, :optional is just a symbol.  So this works:

$ ./gosh -r7
gosh[r7rs.user]> (define (foo a :optional b) (list a :optional b))
foo
gosh[r7rs.user]> (foo 1 2 3)
(1 2 3)

Here, :optional is just another variable.

If you say (define (foo a :optional (b 1)) ...), the (b 1) part violates
R7RS formal parameters.  So it complains.  In 0.9.9, you get
the following error message:

gosh[r7rs.user]> (define (foo a :optional (b 1) (c 2)) (+ a b c))
*** ERROR: Invalid formal parameter: (b 1)
    While compiling "(standard input)" at line 1: (define (foo a :optional
(b 1) (c 2)) (+ a b c))

The trick is that Gauche has two 'define's (and two 'lambda's).   'define'
and 'lambda' in gauche module recognize extended parameters, and 'define'
and 'lambda' in (scheme base) module don't.

(import (only (gauche base) define)) should work.  I see you're using
0.9.6, which is very old.

**Comment by ar-nelson** [comment]
I'm using 0.9.6 because that's what comes with Debian Stable, and so it's a version that I can reasonably expect users of my library to be using.

I don't think that the issue is as simple as `(b 1)` being an invalid parameter. If I use `:optional` in R7RS mode with plain symbol parameters, I get the same error:

```
$ gosh -r7
gosh[r7rs.user]> (define (foo a :optional b c) (+ a b c))
*** ERROR: proper list required for function application or macro use: (b c . #:G176)
    While compiling "(standard input)" at line 1: (define (foo a :optional b c) (+ a b c))
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "/usr/share/gauche-0.9/0.9.6/lib/gauche/interactive.scm":267
```

And maybe this is just an 0.9.6 problem, but `(import (only (gauche base) define))` definitely doesn't work inside an R7RS library, even when I exclude `define` from the `(scheme base)` import.

**Comment by shirok** [comment]
I'm saying those issues are already fixed.

```
gosh[r7rs.user]> (import (except (scheme base) define))
gosh[r7rs.user]> (import (only (gauche base) define gauche-version))
gosh[r7rs.user]> (gauche-version)
"0.9.9"
gosh[r7rs.user]> (define (foo a :optional b c) (+ a b c))
foo
gosh[r7rs.user]> (foo 1 2 3)
6
```

**Comment by shirok** [comment]
I did find another issue, though.  In 0.9.9,  gauche's define inserts `undefined` unhygienically when you don't give the default value.

```
gosh[r7rs.user]> (import (except (scheme base) define))
gosh[r7rs.user]> (import (only (gauche base) define gauche-version))
gosh[r7rs.user]> (define (foo a :optional b) (list a b))
foo
gosh[r7rs.user]> (foo 1)
*** ERROR: unbound variable: undefined
Stack Trace:
_______________________________________
  0  (undefined)
        [unknown location]
  1  (undefined)
        [unknown location]
  2  (eval expr env)
        at "/usr/share/gauche-0.97/0.9.9/lib/gauche/interactive.scm":269
gosh[r7rs.user]> (import (only (gauche base) undefined))
gosh[r7rs.user]> (foo 1)
(1 #<undef>)
```

**Comment by shirok** [comment]
And now...

```
gosh[r7rs.user]> (import (only (gauche base) define))
gosh[r7rs.user]> (import (except (scheme base) define))
gosh[r7rs.user]> (define (foo a :optional b c) (list a b c))
foo
gosh[r7rs.user]> (foo 1 2)
(1 2 #<undef>)
```

**Comment by shirok** [comment]
I'm closing this issue, for it is already addressed in the latest release.  Feel free to reopen it or make a new issue if the related problem persists.
