### ISSUE TITLE
parameterize with more than one binding doesn't allow an internal define

### ISSUE THREAD

**Issue by mnieper** [shirok/Gauche#707]
Consider the following program:

```scheme
(import (scheme base))

(define u (make-parameter #f))
(define v (make-parameter #f))

(parameterize ((u #t) (v #t))
  (define x #f)
  x)
```

Under Gauche 0.9.9, I get the following error:

    *** ERROR: syntax-error: the form can appear only in the toplevel: (define x #f)

When I remove one of the parameter bindings, the program compiles.

**Comment by mnieper** [comment]
I think the problem lies here: https://github.com/shirok/Gauche/blob/master/libsrc/gauche/parameter.scm#L139

In the form with more than one binding, the body of the parameterize form is precomposed with something that is not a definition.

**Comment by shirok** [comment]
You're correct.  I misunderstood the spec.

**Comment by mnieper** [comment]
Thanks. It works here now.
