### ISSUE TITLE
(features) contains a list of all supported SRFIs

### ISSUE THREAD

**Issue by mnieper** [shirok/Gauche#709]
Why does the list returned by (features) contain all supported SRFIs in the form srfi-XXX? As processing a list takes O(n) in the length of the list, a relatively short list is preferred.

For cond-expand, it is not necessary as the existence of SRFIs can be easily tested with (library (srfi XXX)).

**Comment by shirok** [comment]
It is based on the original srfi-0, which didn't have `library` clause.

Now that we have `library` clause and it should be preferred, I should discourage the use of `srfi-XXX`.  There may be code that relies on the current behavior, though, so it'll take some time to gradually retire `srfi-XXX` identifiers.  I can stop adding new `srfi-XXX`, for sure.

**Comment by mnieper** [comment]
Thank you very much for your explanation. I haven't been aware of the fact that SRFI 0 mentions the `srfi-XXX` identifiers.

**Comment by lassik** [comment]
SRFI 0 does mention them, but I can't find any rule in it that requires a feature identifier for each supported SRFI.

SRFI 0 also doesn't require a `(features)` procedure, though R7RS does: "`(features)` Returns a list of the feature identifiers which `cond-expand` treats as true."

Anyway, this means `cond-expand` doesn't need to walk the `(features)` list. The features can internally be in a hash-table (or even a procedure that algorithmically checks a feature with a `srfi-` prefix against the numbers of implemented SRFIs). `(features)` can cons a fresh list; it's not called very often.

**Comment by lassik** [comment]
The O(n) is unlikely to cause a problem in practice, but the feature lists in implementations with many SRFIs do get quite hard to read :)

**Comment by mnieper** [comment]
A user is likely to write something like

(memq 'fantastic (features))

for runtime detection of features.

Am Mo., 3. Aug. 2020 um 19:37 Uhr schrieb Lassi Kortela <
notifications@github.com>:

**Comment by shirok** [comment]
Right that srfi 0 didn't standardized `srfi-XXX` feature identifiers.

But more important point is that, at that time, there was no standard way to "import" a desired library; srfi-0 could be used to import the library portably (across implementations that supported srfi-0).

```
(cond-expand
  (srfi-1))
```
is equivalent to
```
(cond-expand
  ((library (srfi 1)) (import (srfi 1))))
```

**Comment by lassik** [comment]
True. And R6RS still doesn't have a standard `cond-expand`, though that's not a concern for Gauche.
