### ISSUE TITLE
List cycle representation

### ISSUE THREAD

**Issue by jcubic** [shirok/Gauche#713]
I've just fixed cycle representation in my [Scheme based lips in JavaScript](https://jcubic.github.io/lips/), right now in devel branch.

Test case:

```scheme
(define x (let ((x (list 1 (list 2) 3)))
  (set-cdr! (cadr x) (cdr x))
  (set-cdr! (cddr x) x)
  x))
```

I'm using gosh (0.9.9). Output in gosh:
```
#0=(1
    (2
     (2
      (2
       (2 (2 (2 (2 (2 (2 # 3 . #0#) 3 . #0#) 3 . #0#) 3 . #0#) 3 . #0#) 3 . #0#)
       3 . #0#)
      3
      .
      #0#)
     3
     .
     #0#)
    3
    .
    #0#)
```

In my LIPS:
```
#0=(1 #1=(2 . #1#) 3 . #0#)
```
in BiwaScheme it's similar:
```
#0=(1 . #1=((2 . #1#) 3 . #0#))
```
only dot before `#1=` but the value is wrapped in parenthesis so the list is the same.

**Comment by shirok** [comment]
Aha.  That must be a bug in pretty-printer.  Ordinary `write` handles it nicely.

```
gosh> (write x)
#0=(1 . #1=((2 . #1#) 3 . #0#))#<undef>
```

**Comment by jcubic** [comment]
is dot before `#1=` specified somewhere in the standard or maybe SRFI? It looks the same as in BiwaScheme.
I'm not sure if it's worth to make my code work the same.

**Comment by shirok** [comment]
Actually `#0=(1 #1=(2 . #1#) 3 . #0#)` and `#0=(1 . #1=((2 . #1#) 3 . #0#))` are different structures.   See below.

![issue713](https://user-images.githubusercontent.com/190598/89936695-bb847000-dbaf-11ea-830f-511a32617c73.png)

**Comment by shirok** [comment]
Fix pushed.

**Comment by jcubic** [comment]
thanks for the explanation I've already fixed the issue and even the code is simpler.
