### ISSUE TITLE
Support pipes in `process-output->string`?

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#717]
I had to make a pipe and process the output and was disappointed I could not use `process-output->string` (actualy `..->string-list`) for it. I eventually managed to avoid the pipe, but I thought it would be good to bring it up.

Would it be a good idea to support pipes in `process-output->string` in addition to just one command? That makes it a bit more convenient. If we stick to "list of lists" as a pipe syntax, I don't think it'll clash with any current uses of the procedure.

It may open up a new can of worms though. `process-output->string` is just a wrapper of `call-with-input-process` (or `open-input-process-port`). Going that route, one may wonder if it's possible to add pipe support to those too. And that might be a step too far...

**Comment by shirok** [comment]
Interesting idea.  Indeed, we already have pipeline builder code (`run-pipeline`) so it's a matter of hooking up to `open-input-process-port` etc.

**Comment by pclouds** [comment]
Closing this one? I see you already updated both code and documents (and I tested it, it worked)

**Comment by shirok** [comment]
Yup.  Let's close this.
