### ISSUE TITLE
parameter objects are not recognized as procedures

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#720]
r7rs-small writes this

> Returns a newly allocated parameter object, which is a **procedure** that accepts zero arguments and returns the value associated with the parameter object. 

In Gauche, this is not true

```
gosh$ (define a (make-parameter #f))
a
gosh$ (procedure? a)
#f
```

This blocks `(chibi term)` from being installed because its test suite checks this. (This partcular package is of no importance, i just wanted to say where I found the problem)

**Comment by pclouds** [comment]
Actually it might be important. Assuming that chibi-snow is going to take over the world, I want to run it directly on gauche (I need chibi the first time to install chibi-snow on gauche, but after that chibi could be removed). That pulls quite many dependencies and might include this one.

**Comment by shirok** [comment]
Ah, ok.  Hmm... I think there's not much code that depends on the fact that Gauche's parameter is an instance of <parameter>, so we may just change it into a mere procedure (with some hidden protocol to access internal state).

**Comment by pclouds** [comment]
Another interesting note from srfi-39

>  Because it is possible to implement the R5RS procedures current-input-port and current-output-port as parameter objects and this offers added functionnality, it is required by this SRFI that they be implemented as parameter objects created with make-parameter. 

In gauche these are procedures (so technically not parameter objects?), but I haven't checked if they can be passed to parameterize yet. If they are, I suppose they qualify as parameter objects regardless.

r7rs also says they are parameter objects

> The procedures current-input-port and current-output-port are now parameter objects, as is the newly introduced current-error-port

**Comment by shirok** [comment]
`parameterize` works for procedures that follows the protocol---zero argument to return the current value, one argument to alter the current value and returns the previous value.    A simple procedure won't work if you have a converter procedure---in which case parameterize needs the means to bypass the converter procedure to set the value.   `current-input-port` doesn't use converter procedure so it's fine.

**Comment by pclouds** [comment]
```
$ tools/snow-chibi --impls gauche install -v  '(chibi term ansi)'
(installing packages: ((chibi term ansi)) for gauche)
All tests passed.
```

Hurray!
