### ISSUE TITLE
build.configure in version output

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#737]
#736 reminds me, is it possible to add the [`build.configure`](https://srfi.schemers.org/srfi-176/srfi-176.html#_build_properties) property to `-V` output? The information can be already obtained with `gauche-config --reconfigure` but `-V` would have it in a somewhat more standard place.

This would probably imply using `GAUCHE_CONFIGURE_ARGS` from `configure.ac` or adding another slightly differently quoted variant of it.

**Comment by shirok** [comment]
It can be obtained by (cdr (shell-tokenize-string (gauche-config
"--reconfigure")))

But it depends on gauche.config and gauche.process and we want to set
autoload.  Maybe I'll move version-alist to some autoloaded module.

**Comment by lassik** [comment]
Thank you for implementing this.

An alternative would be to move (some of) the data from `gauche-config.c` into a `gauche-config.h` which can be included from more than one place. Then both `gauche-config.c` and Scheme code could use the same values.

Does autoloading `gauche.process` slow down `gosh -V`?

**Comment by lassik** [comment]
In fact, there's a TODO comment in `src/genconfig`:

```shell
# TODO: we have almost exactly the same table in gauche-config.c part
# (cmds[]) and config.scm part (*configurations*).  They should be
# generated from a single source.
```

**Comment by lassik** [comment]
Wait, the current implementation of `version-alist` is not launching a subprocess. Is `gauche.process` used only for `shell-tokenize-string`?

**Comment by shirok** [comment]
> Does autoloading `gauche.process` slow down `gosh -V`?

Technically yes.  It now loads a few modules.   The output can be statically computed, so we can pre-compute it and just embed the result, if the speed matters.

> Wait, the current implementation of `version-alist` is not launching a subprocess. Is `gauche.process` used only for `shell-tokenize-string`?

Yes.

**Comment by lassik** [comment]
This works and can probably be closed. If there's a faster way to output `gosh -V` without loading `gauche.process` by pre-splitting the argument list at build time, that's an optional optimization.
