### ISSUE TITLE
Math - radians->degrees and degrees->radians

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [shirok/Gauche#749]
Hello,

It would be very convenient if the below definitions were part of some Gauche module. Recently I have to define them myself to do some calculations.
```scheme
(use math.const)

(define (radians->degrees r)
  (* r 180/pi))

(define (degrees->radians d)
  (* d pi/180))
```
Would you consider including them as part of Gauche distribution as they are needed when doing trigonometry calculations?

**Comment by shirok** [comment]
It looks reasonable to have them.  Do you know other implementations having those procedures?  If there are, I'd like to have the same name.

**Comment by volodymyrprokopyuk** [comment]
My small and quick investigation on the naming in other Schemes and Lisps
* The names in plural (`radians->degrees` and `degrees->radians`)
  * Racket https://docs.racket-lang.org/reference/generic-numbers.html
  * Commmon Lisp https://common-lisp.net/project/cl-mathstats/documentation/cl-mathstats-package/index.html
* The names in singular (`radian->degree` and `degree->radian`)
  * Chicken 4 (outdated) has the names in singular https://wiki.call-cc.org/eggref/4/2d-primitives
  * Guile https://www.gnu.org/software/guile-cv/manual/html_node/Pi.html

I'd go with the names in plural as is spoken in mathematics. But the choice of naming could also depend on the naming style and consistency in Gauche libraries, however I do not think Gauche strictly follows singular naming everywhere.

**Comment by shirok** [comment]
Thanks!  The fluctuation is a bit concern, but I'd go with plural names.

**Comment by volodymyrprokopyuk** [comment]
Thank you very much!
