### ISSUE TITLE
SRFI 219: Define higher-order lambda

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#754]
Gauche's native `define` already supports this syntax, but for portable code, it would be nice for `(import (srfi 219))` to work.

`gosh -r 7` doesn't seem to support Gauche's extensions to the lambda list syntax (e.g. keyword arguments) whereas `gosh` in native mode does. `(import (srfi 219))` could import either one of these - I don't really have an opinion.

**Comment by pclouds** [comment]
I know I objected it, but I'm not a Scheme implementer and Shiro may think differently. So, maybe this should be considered as well

https://github.com/ashinn/chibi-scheme/pull/740#issuecomment-821988772

**Comment by shirok** [comment]
Hmm, I haven't fully thought about it.  Since the portable code assumes portable `define`, I tend to make `(import (srfi 219))` imports the vanilla one.

**Comment by lassik** [comment]
Sounds reasonable. If the `define` exported by `(srfi 219)` has less features, we can always add more features later. But if we start out supporting all features of Gauche's native `define` now, it's harder to remove features later.

**Comment by lassik** [comment]
The `define` given by `gosh -r 7` also doesn't let the user define keyword arguments.

**Comment by lassik** [comment]
Thanks for implementing this.

Is it intentional that the `define` imported from `(scheme base)` also supports the nesting syntax?

This library:

```Scheme
(define-library (testlib)
  (export main)
  (import (scheme base) (scheme write))
  (begin  (define ((foo a) b) (+ a b))
          (define (main args) (display ((foo 1) 2)) (newline))))
```

when run via `gosh -m testlib testlib.sld` outputs `3`, with or without `-r 7`.

**Comment by shirok** [comment]
@lassik Yes, srfi-219 is a compatible extension of R7RS define, so valid R7RS programs just works. 
I did the same for other extensions such as srfi-61 (extension of `cond`) before R7RS.

OTOH, Gauche's extended lambda formals are, strictly speaking, not compatible to R7RS, so I distinguished it from the vanilla forms.
