### ISSUE TITLE
json-lines-read does not work

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#767]
With the latest Git master:

```
$ echo 123 | gosh -r 7 -e '(import (gauche base) (srfi 180)) (pprint (json-lines-read)) (exit)'
#<closure ((json-lines-read json-lines-read))>
```

**Comment by shirok** [comment]
`json-lines-read` returns a generator.

```
$ echo 123 | gosh -r 7 -e '(import (gauche base) (srfi 180) (scheme generator)) (pprint (generator->list (json-lines-read))) (exit)'
(123)
```

**Comment by lassik** [comment]
You're right. My bad. I was confused by the fact that `json-read` returns an object.

**Comment by Hamayama** [comment]
reference is wrong?
https://github.com/shirok/Gauche/blob/d8618da62b879382f082e775aa7715fe263efe39/doc/modsrfi.texi#L9135

**Comment by shirok** [comment]
@Hamayama you're right.
