### ISSUE TITLE
fresh-line

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#772]
It might not be so hard to have CL's `fresh-line`.  The output port can remember whether the last output was newline or not.  If port position is changed, we can put newline anyway.

It came to me when improving test report output.  The custom report procedure may or may not emit a newline.  If we have `fresh-line` we can avoid an extra empty line.

**Comment by lassik** [comment]
IMHO like `char-ready?`, `fresh-line` usually means something is off about the algorithm design. The participants in the design should agree on something (e.g. who should write a newline) and this has not been decided.

**Comment by pclouds** [comment]
fyi srfi-159 (scheme show) also has this `fl`

**Comment by shirok** [comment]
It cannot be implemented portably, and I don't expect it to be in Scheme (like srfi).  The Scheme way is, as @lassik says, to design things to agree that who emits the newline.

In practice, however, you may mix code from various sources and the upper layer may not know whether there was a newline or not.  For example, you want to emit a separator `=================` to output for readability, and want them to be from the beginning of line.   You have no control on other stuff emitted to the output.  The safe bet is always emit newline before a separator, but that may cause unnecessary empty line.  It works, but it's kind of annoying.

It is more like a personal taste, and I have no intention to suggest it as a general Scheme feature.

@pclouds I believe `fl` only works within `srfi-159`.  It can't know if other library code emitted a newline before `show` is called.

**Comment by shirok** [comment]
I thought it might be implemented portably with srfi-181 custom ports, but actually It can't, for there's no way to distinguish one kind of custom ports from another, and no way to store and provide access to extra states.

**Comment by APIPLM** [comment]
`read` ignore the `newline`, see the source code in the below

`(with-input-from-string "(define-values (displayed written)\n  (let ((repr (lambda (fn)\n                (lambda (object)\n                  (call-with-port (open-output-string)\n                                  (lambda (port)\n                                    (fn object port)\n                                    (get-output-string port)))))))\n    (values (repr display) (repr write))))" (lambda () (read)))
`

`write` is not necessary need `newline`
`display` always is along with `newline`
```

(with-output-to-string
  (lambda ()
    (display "Once upon a time ...")
    (newline))) <graphic> "Once upon a time ...\n"

```

The person who is interactive with output string port will need to manager the `newline`, like when the person create output string `open-output-string` , then have to manager it

**Comment by shirok** [comment]
@APIPLM Sorry I don't get your point.  If there's one person manages all the code, we have no issue.

IMHO, `fresh-line` is very CL-ish.  You have balls of mud and you make a big ball of mud, but want a bit of cosmetics, that's it.  I don't think it fits Scheme's gem.  But Gauche adopts certain muddy flavor by choice.
