### ISSUE TITLE
Can't compile master with error: unbound variable make-parameter

### ISSUE THREAD

**Issue by amirouche** [shirok/Gauche#785]
```
make[2]: Leaving directory '/home/amirouche/src/scheme/live/git/local/tmp/Gauche/gc'
make[1]: Leaving directory '/home/amirouche/src/scheme/live/git/local/tmp/Gauche/gc'
make[1]: Entering directory '/home/amirouche/src/scheme/live/git/local/tmp/Gauche/src'
rm -f gauche/config_threads.h
echo "/* Generated automatically from gc config header; do not edit. */" > gauche/config_threads.h
grep '^#define GC_[0-9A-Z_]*THREADS' ../gc/include/config.h >> gauche/config_threads.h || :
GAUCHE_LOAD_PATH="" GAUCHE_DYNLOAD_PATH="" "/usr/bin/gosh"  -l./preload -I../src -I../lib -I../lib -I. `cat ./features.flags` geninsn ./vminsn.scm
*** ERROR: unbound variable: make-parameter
    While loading "../lib/gauche/cgen/unit.scm" at line 84
    While compiling "../lib/gauche/cgen.scm" at line 42: (define-module gauche.cgen (extend gauche.cgen.unit gauche.cgen.literal gauche.cgen.type gauche.cgen. ...
    While loading "../lib/gauche/cgen.scm" at line 45
    While compiling "./geninsn" at line 39: (use gauche.cgen)
    While loading "./geninsn" at line 39
Stack Trace:
_______________________________________
make[1]: *** [Makefile:289: gauche/vminsn.h] Error 70
make[1]: Leaving directory '/home/amirouche/src/scheme/live/git/local/tmp/Gauche/src'
make: *** [Makefile:45: all] Error 1

%
```

Here is the cli dance:

```
git clean -fxd; ./DIST gen && ./configure --prefix=$SCHEME_LIVE_PREFIX && make
```

Here the configure output:

```
config.status: executing default commands

This Gauche has been configured with the following parameters:
           version: 0.9.11_pre2
         multibyte: utf8
     documentation: Yes
              slib: /usr/share/slib
            thread: pthreads
           tls/ssl: axtls
          CA store: check
  optional modules:  zlib

%
```

**Comment by shirok** [comment]
Which version of Gauche do you have on the platform?  (You need 0.9.10; if you have older one, it explains the error.)

**Comment by amirouche** [comment]
To compile Gauche from git, I need at least Gauche 0.9.10?

**Comment by shirok** [comment]
Yes, you need the latest release.
Alternatively,  https://github.com/shirok/get-gauche can fetch pre-release tarball and install it without requiring pre-built Gauche on the target.  However, pre-release tarball is manually created whenever needs arise, and currently no 0.9.11_pre tarballs is made.  It may be a good idea to add nightly build tarballs.

The way I use in the automated testing system is that I use get-gauche to fetch the latest release, then git clone and build the HEAD.  It always works, though takes time (you build Gauche twice every time).

**Comment by amirouche** [comment]
Thanks for the informations. I managed to compile gauche from the release, and from git. And the JSON tests pass!

**Comment by pclouds** [comment]
Shiro is it possible to add some check in configure.ac to check if we have the right installed version? Could help the users a bit. But if it's significant work, don't bother.

**Comment by shirok** [comment]
Hmm, `configure` can't do the job, for it also runs with the pre-packaged source which doesn't require working Gauche on the target at all.   However, I can make the build bail out early with comprehensive message if it detects version mismatch, I think.
