### ISSUE TITLE
Check build gosh version during building from git

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#786]
Cf. https://github.com/shirok/Gauche/issues/785#issuecomment-983301372

**Comment by shirok** [comment]
One reason I haven't had this is that there's no easy way to determine required version for BUILD_GOSH.  It is "the latest release".  If we're building 0.9.11_pre1, then we can deduce required version is 0.9.10.   However if we're compiling, say, 1.0_pre1, what we need is the 0.9.n where maximum n existing in the release.  

We can fetch it from practical-scheme.net site but we don't require net access during build.    And we want to keep the places to change minimum when we bump versions.

Maybe we keep it near `AC_INIT` in `configure.ac`.

**Comment by lassik** [comment]
Could there be a file in the repo that stores the latest stable version number? If you check out any commit, that file woul automatically have the latest release before that commit.

**Comment by shirok** [comment]
If I use a separate file, I'm afraid that I forget to update it when making a new release.
I added it in `configure.ac` right below the `AC_INIT` line, so I can change these two lines at once when I make a new release.

**Comment by shirok** [comment]
closing.
