### ISSUE TITLE
Self-referencing boxes crash while being printed

### ISSUE THREAD

**Issue by jpellegrini** [shirok/Gauche#787]
Hello,
While working on STklos boxes, @egallesio and I [noticed](https://github.com/egallesio/STklos/issues/306) that Gauche segfaults when a box references itself and is printed:

```
gosh$ (define b (box 1 2))
b
gosh$ 
gosh$ b
#<mv-box[2] 1 2>
gosh$ (set-box-value! b 0 b)
#<undef>
gosh$ b
Segmentation fault
```

**Comment by shirok** [comment]
Good catch!  Fixed.

**Comment by jpellegrini** [comment]
Yes, it works now :)
Thanks for the quick fix.,
