### ISSUE TITLE
changes to sys-tm cause bugs under linux, already shown by 'make check'

### ISSUE THREAD

**Issue by riddochc** [shirok/Gauche#788]
Hi,

Running 'make check' under recent versions of Gauche are failing in the tests for srfi-19.  I've found a simple command to reproduce the issue, and bisected to find the version which causes the issue.

`gosh -u srfi-19 -e "(display (sys-localtime (time-second (current-time))))" -Enewline -Eexit`

At commit 12dab0f00ba0892d12a158181780d6ad4af9ba85 the output is  `#<sys-tm "Fri Dec 17 17:57:01 2021">`

Then, at commit b00e31bbcaf11c881729beca9c7aa0f6734f5075 the output is `#<<sys-tm> 0x7f85c7a19d00>` which looks like a memory address.

In later commits, like 6c21f2124e590fb459fb34eaf6f499ba2b70315e the output is  `#<sys-tm "? ? 32764 1706372576:00:00 ��">` which looks like it's treating something that isn't a sys-tm as though it is one, resulting in garbage data.

I wish I could offer a patch to go with this issue, but I don't yet understand the internals of Gauche and the changes with define-cstruct.  Whatever is needed to be done with migrating sys-tm to use define-cstruct apparently still needs work.

**Comment by riddochc** [comment]
I've just bisected to find where the output of the command I gave changes from something like ` #<<sys-tm> 0x7fcbfe908000>` to something like `#<sys-tm "? ? 32766 319111760:00:00 !c<">`

It looks like bbde155ca4c1a90eebbde42f1c137feba02738bb is where that happens, which makes sense as it's where the printer code is changed to work with define-cstruct's objects.  I think the underlying issue is in how sys-tm is treated differently with define-cstruct starting at b00e31bbcaf11c881729beca9c7aa0f6734f5075 but that's only a guess right now.

Thanks for all your work on Gauche, by the way.  It's a very impressive project.

**Comment by shirok** [comment]
Thanks for catching this. It seems platform-dependent, for it works on Ubuntu/x64/gcc7.5.  It does appear that on your environment invalid pointer is passed to strftime.

**Comment by riddochc** [comment]
Interesting, I'm on opensuse, x64, with gcc 11.2.1.  Specifically, `gcc version 11.2.1 20211124 [revision 7510c23c1ec53aa4a62705f0384079661342ff7b] (SUSE Linux)`

I'm currently looking at the differences between how Scm_MakeSysTm in system.c worked before the introduction of define-cstruct, and how Scm_Make_sys_tm in libsys.c is now generated by the cgen-decl commands in define-cstruct.  I'm not sure I see an equivalent to tm_allocate.  But it's getting late for me, you can probably make more sense of this than I can right now.

**Comment by shirok** [comment]
Ah! Now I see.  The current code passes a local struct to gmtime_r, but we’re using its pointer after its scope ended.  It triggers an undefined behavior.

**Comment by shirok** [comment]
Does https://github.com/shirok/Gauche/commit/2345f756fc536a30e5cf8f8efc7211c8350c8fa8 fix it?

**Comment by riddochc** [comment]
Yes, that fixes it!  Thanks!
