### ISSUE TITLE
Array bounds warning under gcc 11.2.1

### ISSUE THREAD

**Issue by riddochc** [shirok/Gauche#789]
The build's mostly warning-free, which is impressive considering how much more strict gcc has become.  There's only one that looks very meaningful in the entire build, and given the nature of it, it seems worth mentioning:

```
gcc -DHAVE_CONFIG_H -I. -I. -I./../gc/include -I../gc/include `./get-atomic-ops-flags.sh .. .. --cflags`   -g -O2 -Wall -Wextra -Wno-unused-label -fPIC -fomit-frame-pointer  -c vector.c
vector.c: In function ‘Scm_VectorCopy’:
vector.c:114:19: warning: array subscript ‘ScmVector {aka struct ScmVectorRec}[0]’ is partly outside array bounds of ‘unsigned char[16]’ [-Warray-bounds]
  114 |     v->size_flags = (size << 1);
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~
In file included from gauche.h:105,
                 from vector.c:35:
./../gc/include/gc.h:950:24: note: referencing an object of size 16 allocated by ‘GC_malloc’
  950 | # define GC_MALLOC(sz) GC_malloc(sz)
gauche.h:532:35: note: in expansion of macro ‘GC_MALLOC’
  532 | #define SCM_MALLOC(size)          GC_MALLOC(size)
      |                                   ^~~~~~~~~
gauche.h:539:39: note: in expansion of macro ‘SCM_MALLOC’
  539 | #define SCM_NEW2(type, size)  ((type)(SCM_MALLOC(size)))
      |                                       ^~~~~~~~~~
vector.c:110:20: note: in expansion of macro ‘SCM_NEW2’
  110 |     ScmVector *v = SCM_NEW2(ScmVector *,
      |                    ^~~~~~~~
```

**Comment by shirok** [comment]
Very impressive that gcc catches it.   Indeed, if we allocate zero-length vector, it allocates smaller than sizeof(ScmVector).  Gauche never accesses the out-of-boundary but it is a violation anyway.

**Comment by riddochc** [comment]
The warning's gone, all tests pass.  There's a few other warnings, but I don't expect they have as much significance.   I'll just attach a shell log of the whole generate/build/test process for you to see what it looks like on my system, for any comparison purposes you like.  It was produced by the 'script' program so it has all of GCC's ANSI colors included with the terminal escape sequences.  Anyway, the zero-length vector looks fixed, thanks!

[gauche-build.txt](https://github.com/shirok/Gauche/files/7740047/gauche-build.txt)
