### ISSUE TITLE
`pthread_cancel` not available on Android

### ISSUE THREAD

**Issue by xtkoba** [shirok/Gauche#790]
`pthread_cancel` is not available on Android, and the following part needs some modification:

https://github.com/shirok/Gauche/blob/fc0c7f0d6176bbb3fbf6179139577ea28231bc82/ext/threads/threads.c#L485

Is it safe if simply removed?

**Comment by shirok** [comment]
Oh, ok.  If you don't have `pthread_cancel`, there can be cases that you can't terminate a thread.   But terminating thread forcibly is the last resort and an inherently dangerous operation, and won't be called unless you ask to do so.   If you don't have `pthread_cancel`, then there's no choice but omit it.

I'll add a configure test to check its availability and `#ifdef` there.

**Comment by xtkoba** [comment]
Thanks!

**Comment by shirok** [comment]
Closing.
