### ISSUE TITLE
= can be not transitive

### ISSUE THREAD

**Issue by FrankHB** [shirok/Gauche#805]
R7RS requires `=` to be transitive.

However, with a case from [this page](https://codewords.recurse.com/issues/one/when-is-equality-transitive-and-other-floating-point-curiosities): `(= 9007199254740992.0 9007199254740993)` => `#t`.

This is not conforming. The requirement is same from R5RS to R7RS, and there is a note in R7RS stating "the implementation  approach of converting all arguments to inexact numbers if any argument is inexact is not transitive".

(I'm not sure whether this is intended in R6RS, since [this ticket](https://small.r7rs.org/ticket/367/) suggests inexact contagion is allowed generally.)

**Comment by shirok** [comment]
Good catch.

**Comment by shirok** [comment]
Actually, I had code for this.  It wasn't exhausitive.

**Comment by shirok** [comment]
Fixed.
