### ISSUE TITLE
port-tell is not the same as ftell

### ISSUE THREAD

**Issue by tizoc** [shirok/Gauche#81]
When opening a file in append mode, `port-tell` returns 0, even when the file has contents in it. Then after writting data to the file, the result of `port-tell` increases the same as the amount of bytes written, but this is still relative to 0 (so, after opening a file with 40 bytes on it, and writing 4 bytes more, `port-tell` returns 4 instead of 44).

When using `ftell` in C, the result of calling it after opening a file in append mode, is the amount of bytes in the file.

I see that `port-tell` in Gauche is defined in terms of `port-seek` (which I assume is `fseek`), but the result of this is that the behaviour is a bit surprising: https://github.com/shirok/Gauche/blob/39d1a65c1b81d478b7432ab965827e677b469ae0/src/libio.scm#L371

If an `(port-seek port 0 SEEK_END)` call is made to explicitly set the stream position at the end, then the results of calling `port-tell` start being the expected ones.

Example Scheme program to reproduce this.

```scheme
(define f (open-output-file "/tmp/append-test" :if-exists :append :if-does-not-exist :create))

(display (port-tell f)) ;; displays 0
(newline)
(display "1234" f)
(display (port-tell f)) ;; displays 4
(newline)
(port-seek f 0 SEEK_END)
(display (port-tell f)) ;; displays 44 (file started with 40 bytes)
(newline)
(display "5678" f)
(display (port-tell f)) ;; displays 48 as expected
(newline)

(close-output-port f)
```

Example C program to see the behaviour of using `ftell` after opening a file in append mode:

```c
#include <stdio.h>

int main() {
  FILE *f = fopen("/tmp/append-test", "a");
  printf("%ld\n", ftell(f));
  fclose(f);
  return 0;
}
```

**Comment by shirok** [comment]
Thanks to catch this.  `Port-seek` eventually calls lseek instead of fseek, for we don't use FILE* layer, but it's effectively the same for this issue.  The problem is that `port-seek` tries to "optimize", that is, it avoids calling lseek if we "know" the current position.  And the appending case we incorrectly assume we know the initial position.   Will fix.

**Comment by tizoc** [comment]
Thanks. Btw, Gauche's manual points out the equivalence between `port-tell` and `port-seek`, it just happens to be confusing in this particular case.

I found a similar (but different) issue in chibi-scheme, already reported it.

**Comment by shirok** [comment]
Oops, nope, the analysis above was wrong.  We do call lseek(2) in the case of initial `port-tell` right after appending open, *and lseek(2) returns zero in that case*.  It seems that we need explicit seek to the end to make lseek return a correct number.

**Comment by shirok** [comment]
Fix pushed https://github.com/shirok/Gauche/commit/946ac64bdb4a31e70be25c5f53077ee77f940848
