### ISSUE TITLE
Confusing error message for list-ref

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#814]
When `list-ref` is given something other than a list, it says `argument out of range` instead of `not a list`.

```
gosh[r7rs.user]$ (list-ref (vector) 0)
*** ERROR: argument out of range: 0
[...]

gosh[r7rs.user]$ (list-ref 'foo 0)
*** ERROR: argument out of range: 0
[...]
```

**Comment by shirok** [comment]
Technically, Gauche's `list-ref` accepts dotted list and `'foo` is a dotted list of length 0.  So the error message should be the same as `(list-ref '() 0)` or `(list-ref '(a . b) 1)`.

But passing length 0 list (proper or dotted) to `list-ref` is useless anyway.  So we can require it to be a pair.

**Comment by shirok** [comment]
The above fix was incorrect.   `(list-ref 'a 0 'foo)` is a valid call (returns `foo`).

**Comment by shirok** [comment]
Changed to specifically check the case fallback is not given.
