### ISSUE TITLE
Compiling cgen generated code with c++: 'warning: cast to pointer from integer of different size'

### ISSUE THREAD

**Issue by fbrosda** [shirok/Gauche#815]
Hi,

since Gauche 0.9.11 I get a warning, when compiling with cgen generated code with a c++ compiler (gcc 11.2.0):

```
In file included from grtc5fee0432.c:2:
/usr/lib/gauche-0.98/0.9.11/include/gauche.h:289:28: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  289 | #define SCM_OBJ(obj)      ((ScmObj)(obj))
      |                            ^~~~~~~~~~~~~
/usr/lib/gauche-0.98/0.9.11/include/gauche/vector.h:68:5: note: in expansion of macro ‘SCM_OBJ’
   68 |     SCM_OBJ(((len)<<1)|(imm?1:0))
      |     ^~~~~~~
grtc5fee0432.scm:137:5: note: in expansion of macro ‘SCM_VECTOR_SIZE_SLOT_INITIALIZER’
```

From my understanding, the issue is the part `imm?1:0`, which in c++ is implicitly cast to an integer first and then casting it to a pointer emits the above warning. The code works still as expected, but the warning is a bit annoying. 

I think doing something like `imm?SCM_OBJ(1):SCM_OBJ(0)` would stop the compiler from complaining, because then it's clear, that the types inside the ternary operator are `ScmObj`.

Compiling with the C compiler does not produce any warnings.

**Comment by shirok** [comment]
Thanks for reporting.  How about the commit above?

**Comment by fbrosda** [comment]
Looks good and works as expected for me. Thanks a lot for the very quick reply.
