### ISSUE TITLE
(uvector-size (make-u8vector (ash 1 32))) => 0

### ISSUE THREAD

**Issue by karme** [shirok/Gauche#816]
gosh$ (use gauche.uvector)
gosh$ (uvector-size (make-u8vector (ash 1 32)))
0

**Comment by shirok** [comment]
Good catch.  Remnant of 32bit era.

**Comment by karme** [comment]
maybe the test is a bit optimistic/demanding regarding build host specs?  I still use virtual machines with less than 4G RAM to build gauche

**Comment by shirok** [comment]
Hmm, true.  I commented out the test.

**Comment by karme** [comment]
gosh$ (use gauche.uvector)
gosh$ (uvector-size (make-u8vector (ash 1 32)))
4294967296
