### ISSUE TITLE
Fix connection protocol in tls layer

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#818]
We're moving away from dealing with the raw socket (mbedTLS3 doesn't allow us to get the underlying socket).  Currently the connection protocol implementation in tls abstraction layer relies on the underlying socket access.  We need to get rid of that code.  Instead, each TLS implementation layer needs to provide getpeername etc.

**Comment by Hamayama** [comment]
あまりよく分かっていないのですが、

MbedTLS 3.1 で、

mbedtls_net_context の fd が、public に戻されたという情報があるようです。

https://libwebsockets.org/git/libwebsockets/commit/lib/tls/tls-jit-trust.c?id=954dd39756e70f71328ffb52d28032e14ad464f2

https://github.com/Mbed-TLS/mbedtls/commit/b11d61e095dd656afec02716f350db1e2063a8b9

**Comment by shirok** [comment]
@Hamayama 他にも困ってた人いたのかな。ともあれ、生fdに触らなくて良いならそれに越したことはないので、その方向で考えてみます。

**Comment by shirok** [comment]
Hmm, MbedTLS 3.0 doesn't expose underlying fd for any way, so we can't provide `connection-self-address`/`connection-peer-address`.

**Comment by shirok** [comment]
MbedTLSも3.1以降fdをpublicに戻すなら、3.0だけ特別扱いで #820 を頂いてもいいかなという気になっています。
