### ISSUE TITLE
SRFI for Gauche's Object System

### ISSUE THREAD

**Issue by stew-j** [shirok/Gauche#834]

**Comment by stew-j** [comment]
In fact, STklos was originally the Scheme that the University of Oregon's CS department (in 1996) used to wrap the C++ graphics library I currently use:

[1] https://www.cs.uoregon.edu/research/paraducks/papers/tr9605.d/

I reimplemented their reactive visualization system in my Common Lisp version, as I could not find their software "Viz".

[1] Harold H. Hersey, Steven T. Hackstadt, Lars T. Hansen and Allen D. Malony, Viz: A Visualization Programming System, University of Oregon, Department of Computer and Information Science, Technical Report CIS-TR-96-05, April 1996.

**Comment by stew-j** [comment]
Getting a little off topic, but a couple of samples I got working from Viz in 2018.

https://github.com/stew-j/portfolio/blob/main/program-1.lisp
https://github.com/stew-j/portfolio/blob/main/program-2.lisp

This is the kind of thing I would like to do with a Scheme object system.

**Comment by stew-j** [comment]
Just a stub for now, but I've been thinking about :before, :after, and :around auxiliary methods in CL--Gauche doesn't seem to support these.  I don't use them too often, there should be alternate ways of implementing them:  ```next-method```, etc.

**Comment by shirok** [comment]
@stew-j You may have a reason to delete them, but I don't mind at all keeping your comments here---some ideas may be revitalized later.
