### ISSUE TITLE
(peek-char) and (peek-byte) consume EOF

### ISSUE THREAD

**Issue by petelliott** [shirok/Gauche#837]
This is only a problem in TTYs where the next `read(2)` after an EOF will not be an EOF.

The issue is that `PORT_UNGOTTEN(p) == SCM_CHAR_INVALID` is treated as empty, but `SCM_CHAR_INVALID == EOF == -1`.

## reproducing
```scheme
gosh$ (begin (peek-char) (peek-char) (read-char))
```

**Comment by shirok** [comment]
confirmed.
