### ISSUE TITLE
idea: Tee port

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#870]
`(open-tee-port iport oport) => #<iport>`.  A thread runs to keep copying the data from iport to oport, while the data is also available to read from the returned port.

If the returned port is closed, the thread just keep copying the data.  If oport is closed, the thread just keep making the data available for the returned port.  Both oport and returned port is closed, the thread terminates.

Useful to insert to, say, log output stream, so that keep reporting log to stderr but also the program can pattern-match the output to take some other actions.

**Comment by lassik** [comment]
Common Lisp has [`broadcast-stream`](https://clhs.lisp.fi/Body/t_broadc.htm#broadcast-stream) which is similar but not identical.

**Comment by shirok** [comment]
`broadcast-stream` is to "push" the data into both streams; what I want is that it pushes to one stream (oport), but can be pulled from another (the returned port).  But the name "tee" might be taken as the former.  "Tap" may be better.

**Comment by shirok** [comment]
This is realized as `control.plumbing` module.   https://practical-scheme.net/gauche/man/?p=control.plumbing&v=draft
