### ISSUE TITLE
Multiple internal definitions use the first binding

### ISSUE THREAD

**Issue by leahneukirchen** [shirok/Gauche#872]
```
(let () (define x 5) (define x 6) x)
```
evaluates to 5.

Other Schemes evaluate to 6 or raise an error due to duplicate definition. Gauche's behavior is suprising at least. :)

(I favor evaluating to 6 for consistency with toplevel definitions.)

**Comment by shirok** [comment]
Thanks for pointing this out.  Gauche is rather lazy about detecting this kind of errors, assuming programmers don't write such code---if the program is invalid, we can make up any result.  But certainly this result is rather surprising.
