### ISSUE TITLE
Handle leak by open-output-string on Windows

### ISSUE THREAD

**Issue by Hamayama** [shirok/Gauche#951]
以下の処理で、Windows のハンドル数が増加します (添付画像)。

```
(let loop () (open-output-string) (loop))
```

ハンドル数が、16,000,000 くらいまでいくと、
Gauche が強制的に終了します (エラー等は出ない) 。

Gauche 0.9.13 で発生します。

Gauche 0.9.12 以前では発生しません (6000 くらいまでは増加しますが、GC に回収されます)

open-output-string は、number->string でも使われているみたいで、
(x->string 数値) で気が付きました。

#900 の関連かとも思いますが、
ちょっとよく分からないので、まずは情報として挙げておきます。

＜添付画像＞
![taskmng1](https://github.com/shirok/Gauche/assets/4497079/a0be5e26-c634-4f7e-ae57-72fc376161d2)

**Comment by shirok** [comment]
Thanks for reporting.  `open-output-string` は純粋にメモリ上の操作でファイルハンドルは使ってないはずなんですが、妙ですね…

**Comment by shirok** [comment]
あー多分わかりました。

- コミット https://github.com/shirok/Gauche/commit/1ed58ae7db3a58a3d5dd79d699015be73d0e0f8c で、文字列ポートではファイナライザを呼ばないようにした (かなり速くなる)
- だが、MinGWではポートのfastlockにも通常のmutexが使われていて、これはハンドルを消費する。closeが呼ばれないとこのハンドルが回収されない。

**Comment by Hamayama** [comment]
ありがとうございます。

コミット c1bf6bb (2023-10-21) で、修正されていることを確認しました。
