### ISSUE TITLE
Behavior of format using slib

### ISSUE THREAD

**Issue by fbrosda** [shirok/Gauche#960]
The issue is first about the behavior of format, when slib is used. There is a old note in the changelog, that `(use slib)` should not load srfi-29 to avoid overwriting the internal version of format, s.a. https://github.com/shirok/Gauche/blob/master/ChangeLog#L17866

I did not find anything that this was changed intentionally, but at least since v0.9.10 this does not work and `(use slib)` will load the version of format from srfi-29.

See below for examples of the different cases.

Until now my workaround was to `(use srfi-28)` after including slib, which again loaded a correct version of format. But this stopped working with v0.9.13. There only `(use srfi.28)` seems to load it correctly. 

Wrapping up, there are two points

1. What's the intended behavior for slib and format? I'm fine with the status quo, as long as the workaround works
2. Why does `(use srfi-28)` behave differently then `(use srfi.28)`?

```
$ gosh -V
Gauche scheme shell, version 0.9.10 [utf-8,pthreads], x86_64-pc-linux-gnu
(version "0.9.10")
(command "gosh")
(scheme.id gauche)
(languages scheme r5rs r7rs)
(encodings utf-8)
(website "https://practical-scheme.net/gauche")
(build.platform "x86_64-pc-linux-gnu")
(scheme.path "/usr/share/gauche-0.97/site/lib" "/usr/share/gauche-0.97/0.9.10/lib")
(gauche.threads pthreads)
(gauche.net.tls axtls)

$ gosh
gosh> (use slib)
gosh> (format (current-error-port) "TEST")
*** ERROR: string required, but got #<oport (standard error output) 0x7f78ce8f9e00>
Stack Trace:
_______________________________________
  0  (string->list format-string)
        at "/usr/share/gauche-0.97/0.9.10/lib/srfi-29/format.scm":36
  1  (eval expr env)
        at "/usr/share/gauche-0.97/0.9.10/lib/gauche/interactive.scm":303

$ gosh
gosh> (use slib)
gosh> (use srfi-28)
gosh> (format (current-error-port) "TEST")
TEST#<undef>
```

```
$ gosh -V
Gauche scheme shell, version 0.9.13 [utf-8,pthreads], x86_64-pc-linux-gnu
(version "0.9.13")
(command "gosh")
(scheme.id gauche)
(languages scheme r5rs r7rs)
(encodings utf-8)
(website "https://practical-scheme.net/gauche")
(build.platform "x86_64-pc-linux-gnu")
(build.configure)
(scheme.path "/usr/share/gauche-0.98/site/lib" "/usr/share/gauche-0.98/0.9.13/lib")
(threads pthreads)
(gauche.net.tls mbedtls)

$ gosh
gosh$ (use slib)
gosh$ (format (current-error-port) "TEST")
*** ERROR: <string> required, but got #<oport (standard error output) 0x7f564a9d4cc0>
Stack Trace:
_______________________________________
  0  (report-error e)
  1  (string->list format-string)
        at "/usr/share/gauche-0.98/0.9.13/lib/srfi/29/format.scm":36
  2  (eval expr env)
        at "/usr/share/gauche-0.98/0.9.13/lib/gauche/interactive.scm":359
  3  (evaluator exp (vm-current-module))
  4  (with-error-handler (^e (report-error e) #t) (^ () (let loop2 ...

$ gosh
gosh$ (use slib)
gosh$ (use srfi-28)
gosh$ (format (current-error-port) "TEST")
*** ERROR: <string> required, but got #<oport (standard error output) 0x7fc08d82fcc0>
Stack Trace:
_______________________________________
  0  (report-error e)
  1  (string->list format-string)
        at "/usr/share/gauche-0.98/0.9.13/lib/srfi/29/format.scm":36
  2  (eval expr env)
        at "/usr/share/gauche-0.98/0.9.13/lib/gauche/interactive.scm":359
  3  (evaluator exp (vm-current-module))
  4  (with-error-handler (^e (report-error e) #t) (^ () (let loop2 ...

$ gosh
gosh$ (use slib)
gosh$ (use srfi.28)
gosh$ (format (current-error-port) "TEST")
TEST#<undef>
```

**Comment by shirok** [comment]
For the first point -- It doesn't seem to be an intended behavior; indeed, the current comment and code in `lib/slib.scm` contradict to each other.  I suspect I introduced a bug when updated `slib.scm` based on the newer template.   Try the new commit - it should restore the old behavior.

For the difference of `(use srfi-28)` and `(use srfi.28)`, I can't put a finger immediately.  Actually, using `srfi.28` does not load a file; the feature is built-in, so the system treats it as loaded already.  That's something to do with this behavior.

**Comment by fbrosda** [comment]
I can confirm. In the latest version using slib, does no longer break format. Thanks.

**Comment by shirok** [comment]
Ok, found the cause of `(use srfi-28)` weirdness--it's a lurking code that become obsolete but had been harmless until we switch `srfi-N` to `srfi.N`.

**Comment by fbrosda** [comment]
Works as well. Thanks again.
