### ISSUE TITLE
UTF8 BOM handling

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#966]
Currently we don't handle BOM at the beginning of utf8 stream.   The idea is to let applications handle it if needed.  However, it may cause confusion as reported here:

https://sourceforge.net/p/gauche/mailman/gauche-devel/thread/20231205172341.4ec6c98a9787a6cb57ba8b97%40freeshell.org/#msg58709696

We certainly don't want to let every casual script consider the possibility of extra BOM.   Besides, if the input file encoding is UTF-16 or UTF-32, BOM is consumed by the character conversion port, so the behavior looks inconsistent.

If we strictly distinguish textual port and binary port, we may make textual port reading utf8 to drop the BOM.  However, we allow textual/binary mix, we can't simply drop it---for binary stream it changes the content.

One idea is to introduce a pseudo encoding such as `utf-8-bom`, which drops BOM if it exists.

**Comment by Hamayama** [comment]
本件ですが、単純に BOM を削除すると、
フィルターのようなスクリプトを作成した際に、

UTF-8 BOM あり → UTF-8 BOM なし
と変換されてしまい、BOM ありとなしのファイルが、混在してしまったことがありました。

そのときは、以下のようなコードで対応しました。
```
(define (check-and-output-utf-8-bom)
  (when (and (ces-equivalent? *file-encoding* "utf-8")
             *check-utf-8-bom*)
    (let ((b1 (read-byte))
          (b2 (read-byte))
          (b3 (read-byte)))
      (cond
       ((and (= b1 #xef) (= b2 #xbb) (= b3 #xbf))
        (write-byte b1)
        (write-byte b2)
        (write-byte b3))
       (else
        (set-port-position! (current-input-port) 0))))))
```

エンコーディングに utf-8-bom を追加することは、
(1) ces-guess-from-string を使用している既存のスクリプトに影響が出る。
(2) ces-equivalent? で、utf-8 と utf-8-bom は #t になるのか #f になるのか?
(3) iconv が utf-8-bom をサポートしていない。

あたりが気になります。

**Comment by shirok** [comment]
The idea of `utf-8-bom` is that we keep the default behavior intact, and only when the caller explicitly tells Gauche to drop BOM (if there's one), we drop it.    So, `ces-vuess-from-string` never returns `utf-8-bom`.

The 'known' encodings are intercepted by Gauche and handled internally, so iconv won't see it.

The question about `ces-equivalent?` seems interesting.   I think it should be `#f`, for `ces-equivalent?` is used to determine whether the conversion is needed at all.

**Comment by Hamayama** [comment]
なるほど、そうすると、ファイル出力のエンコーディングに utf-8-bom を指定した場合には、
(BOM を出力するのではなくて) エラーにする感じでしょうか?
