### ISSUE TITLE
current-output-port is changed in substitution procedure of regexp-replace

### ISSUE THREAD

**Issue by tsahara** [shirok/Gauche#967]
current-output-port does not work as expected in substitution procedure of regexp-replace. The strings written to the port are appeared in substituted string.

```scheme
(define (proc _)
  (display "proc is called\n")
  "returned")

(format #t "replaced -> ~s~%" (regexp-replace #/./ "a" proc))
```

What I expected:

```
% gosh e.scm
proc is called
replaced -> "returned"
```

gosh actually writes:

```
% gosh a.scm
replaced -> "proc is called\nreturned"
```

**Comment by shirok** [comment]
Indeed.  It is an oversight.

**Comment by shirok** [comment]
Fixed.

**Comment by tsahara** [comment]
Confirmed it has been fixed on master.  Thank you!
