### ISSUE TITLE
Memory leak, when using mbedtls

### ISSUE THREAD

**Issue by fbrosda** [shirok/Gauche#975]
I think I found a memory leak, when doing repeated GET or POST requests with `rfc.http` and TLS.

A minimal example looks like this:

```
#!/bin/sh
#| -*- mode: scheme; coding: utf-8; -*- |#
:; exec gosh -I. -- $0 "$@"
(use rfc.http)

(define (main args)
  (print (sys-getpid))
  (sys-sleep 10)
  (dotimes (200)
    (http-get "www.example.com" "/" :secure #t))
  0)
```

Tracking the memory consumption via `psrecord`

With `:secure #t` 

![memory_https](https://github.com/shirok/Gauche/assets/4280080/74b8a877-265d-47ea-8efe-65995f9ce875)

and compared to that with `:secure #f`

![memory_http](https://github.com/shirok/Gauche/assets/4280080/6a0516d5-4f94-4cad-9e24-ea9c3c3ad8ee)

Instead of using `psrecord` you can also observe how the memory increases via `top -p <pid>`

Used gauche version:

```
$ gosh -V
Gauche scheme shell, version 0.9.13 [utf-8,pthreads], x86_64-pc-linux-gnu
(version "0.9.13")
(command "gosh")
(scheme.id gauche)
(languages scheme r5rs r7rs)
(encodings utf-8)
(website "https://practical-scheme.net/gauche")
(build.platform "x86_64-pc-linux-gnu")
(build.configure "--prefix=/usr" "--enable-multibyte=utf-8" "--enable-threads=pthreads" "--with-slib=/usr/share/slib" "--with-tls=mbedtls" "CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection" "LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now")
(scheme.path "/usr/share/gauche-0.98/site/lib" "/usr/share/gauche-0.98/0.9.13/lib")
(threads pthreads)
(gauche.net.tls mbedtls)
```

**Comment by shirok** [comment]
Oh yeah, it leaked like a broken faucet.  I think the commit fixes it.

**Comment by fbrosda** [comment]
Tested it and now memory usage looks very similar between the tls and non-tls run :+1: 

Thanks a lot for the, as usual, super fast fix.
