### ISSUE TITLE
Suspicious rfc.tls test failure ('double free or corruption)

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#976]
Have seen this second time locally.  `rfc.tls` test aborts with message "double free or corruption (fasttop)".  Can't reproduce.

**Comment by Hamayama** [comment]
Mbed-TLS の issues 3544 (相手側からのリンクを避けるため直URLは載せないでおきます) に、

MBEDTLS_THREADING_C と MBEDTLS_THREADING_PTHREAD がデフォルト無効なので、

マルチスレッドで使うと、上記エラーが出るというような記載がありました。

(ただ、再現できないと分からないと思いますが…)

まずは、弱い情報としてあげておきます。

**Comment by shirok** [comment]
Oh... これは要チェックですね。システムのlibmbedtlsがマルチスレッド有効でなかったら自前で持つしかなさそう。

**Comment by shirok** [comment]
Regarding thread safety of mbedtls:  It appears that almost all mutable states are on various context objects, so we can be careful not to access them from multiple threads.  Currently each `<tls>` object keepts its own contexts separately, so it is achievable.

The only global state I see is its memory allocator.  There's an interface to use custom allocator if configured so.  We may check if we can use it to provide thread-safe allcator.

**Comment by shirok** [comment]
It looks like, at least, debian package of mbedtls is shipped with treading enabled.  We should take care of `mbedtls-internal` case.

**Comment by shirok** [comment]
Close for now.  Reopen if the symptom reappears.
