### ISSUE TITLE
run install-info at installation?

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#988]
This may be a stupid idea, but anyway I've been opening gauche info files manually by C-u C-h i in emacs. I just found out today I could just add gauche info path in emacs so I don't have to type the path every time. Problem is the "dir" file is not generated by gauche so I need to run install-info manually (I install gauche into a separate dir from system, not sure if that matters).

But anyway perhaps gauche can just run install-info at installation time? I think the command is

    install-info --info-dir=$(infodir) [path of info files]

**Comment by shirok** [comment]
Might be a good idea. 

It didn't occur to me, for I usually open info with this:

```
(defun gauche-info-index (topic)
  (interactive
   (list (read-string
          (concat "Gauche help topic : ")
          (current-word))))
  (switch-to-buffer-other-window (get-buffer-create "*info*"))
  (info "/usr/share/info/gauche-refe.info.gz")
  (Info-index topic))

(define-key global-map "\C-xH" 'gauche-info-index)
```

**Comment by pclouds** [comment]
I looked a bit more into this to see how other packages do it (or whether it's the distro's job to generate "dir" files after installation). At least for automake-based programs

> By default, make install-info and make uninstall-info will try to run the install-info program (if available) to update (or create/remove) the ${infodir}/dir index. If this is undesired, it can be prevented by exporting the AM_UPDATE_INFO_DIR variable to "no". 

https://www.gnu.org/software/automake/manual/html_node/Texinfo.html

**Comment by shirok** [comment]
Have been thinking this for a while.  One problem is when we install for creating tarball (when `DESTDIR` is not empty).  We don't want to create `dir` in that case.  Autmake doesn't seem to care in that case, though.

I'm tempted to add info mode to `gauche-install` that checks the conditions and call `install-info` when it's appropriate.

**Comment by shirok** [comment]
Actually, we avoid using `gauche-insall` since it may not be available during installing Gauche itself.

Changed configure.ac and makefile so that it use `install-info` if it's available, and `DESTDIR` is not set.

**Comment by pclouds** [comment]
Makes sense to do nothing when DESTDIR is set but that makes me wonder how distros deal with this (none if the would install directly to root fs). I'll check and report back if I find anything.

**Comment by pclouds** [comment]
Gentoo has a post-install step to [scan and update info dir](https://github.com/gentoo/portage/blob/master/lib/portage/util/_info_files.py#L36). Debian also has [dh_installinfo](https://manpages.debian.org/testing/debhelper/dh_installinfo.1.en.html) which is probably part of a debian package, but I don't know debian format well to know for sure.
