### ISSUE TITLE
SRFI 194 make-random-real-generator incorrect behavior when argument is out of range

### ISSUE THREAD

**Issue by a2378** [shirok/Gauche#994]
~When SRFI-194's make-random-real-generator is supplied with a bounds argument outside the IEEE 754 range, it will always return 3.4028234663852886e38, the max float value.~

Info:
```
(version "0.9.14")
(command "gosh")
(scheme.id gauche)
(languages scheme r5rs r7rs)
(encodings utf-8)
(website "https://practical-scheme.net/gauche")
(build.platform "aarch64-apple-darwin23.3.0")
(build.configure)
(scheme.path "/usr/local/share/gauche-0.98/site/lib" "/usr/local/share/gauche-0.98/0.9.14/lib")
(threads pthreads)
(gauche.net.tls)
```

**Comment by a2378** [comment]
Sorry about that, there was an issue with my code, not with Gauche. Closing.

**Comment by shirok** [comment]
Yeah, I was trying the code and it was not immediately obvious---`(- m)` and `(- m 1)` mean totally different things.  I think it's a historical wart.
