### ISSUE TITLE
hash-table-default! typo in documents

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#995]
```
 -- Function: hash-table-update!/default ht key updater default
     [R7RS hash-table] This is the same as Gauche’s
     ‘hash-table-default!’, except that the default value can’t be
     omitted.
```

but I cannot find `hash-table-default!` anywhere, including all git history. Looking at the code, perhaps this is `hash-table-update!`?

Umm.. I just noticed the japanese part now

```
+@c JP
+これは@var{default}が省略できないことを除けば、
+Gaucheの@code{hash-table-update!}と同じです。
```

I understand the last line at least :)

**Comment by shirok** [comment]
Ooh, right.  I guess I copied the entry and removed a wrong part of it.
